// Visualización de la nueva disposición de botones en Home
console.log('🏠 NUEVA DISPOSICIÓN EN HOME:');
console.log('');
console.log('📱 HEADERBAR (simplificada):');
console.log('   [📱 SplitSmart]                    [👥] [🌙] [🌐]');
console.log('   • Solo título a la izquierda');
console.log('   • Amigos, tema e idioma a la derecha');
console.log('   • Sin avatar (movido abajo)');
console.log('');
console.log('📋 CONTENIDO PRINCIPAL:');
console.log('   • Barra de búsqueda');
console.log('   • Lista de eventos / Estado vacío');
console.log('');
console.log('🎯 BOTONES FLOTANTES (columna vertical, abajo derecha):');
console.log('   ┌─────────────────┐');
console.log('   │        [+]      │  ← FAB Crear Evento (azul)');
console.log('   │         ↕       │');
console.log('   │       [👤]      │  ← FAB Perfil con Avatar (blanco con borde azul)');
console.log('   └─────────────────┘');
console.log('');
console.log('✨ VENTAJAS DEL NUEVO DISEÑO:');
console.log('   ✅ HeaderBar más limpio y minimalista');
console.log('   ✅ Acceso rápido a perfil junto con crear evento');
console.log('   ✅ Dos acciones principales bien visibles');
console.log('   ✅ Avatar del usuario más grande y prominente');
console.log('   ✅ Mejor uso del espacio vertical');
console.log('');
console.log('🎨 ESTÉTICA:');
console.log('   • FAB Crear: Fondo azul primario + ícono blanco +');
console.log('   • FAB Perfil: Fondo blanco + borde azul + avatar usuario');
console.log('   • Ambos con sombra y elevación');
console.log('   • Separados por 16px verticalmente');
console.log('');