import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'pt';

// Traducciones adicionales para español
const additionalEsTranslations = {
  'common.appName': 'SplitSmart',
  'common.cancel': 'Cancelar',
  'common.save': 'Guardar',
  'common.delete': 'Eliminar',
  'common.edit': 'Editar',
  'common.success': 'Éxito',
  'common.error': 'Error',
  'common.add': 'Agregar',
  'common.search': 'Buscar',
  'participants.title': 'Participantes',
  'participants.search': 'Buscar participantes...',
  'participants.noParticipants': 'No hay participantes',
  'participants.noParticipantsDesc': 'Agrega participantes para dividir los gastos',
  'participants.balance': 'Balance',
  'participants.owes': 'Se le debe',
  'participants.shouldPay': 'Debe pagar',
  'participants.balanced': 'Equilibrado',
  'participants.contactInfo': 'Información de Contacto',
  'participants.additionalInfo': 'Información Adicional',
  'participants.addedToEvent': 'Agregado al evento',
  'participants.noContactInfo': 'No hay información de contacto disponible',
  'participants.friendPermanent': 'Amigo Permanente',
  'participants.temporaryParticipant': 'Participante Temporal',
  'expenses.title': 'Gastos',
  'expenses.search': 'Buscar gastos...',
  'expenses.noExpenses': 'No hay gastos',
  'expenses.noExpensesDesc': 'Agrega gastos para comenzar a dividir cuentas',
  'expenses.noResults': 'No se encontraron gastos',
  'expenses.noResultsDesc': 'Intenta con otros criterios de búsqueda',
  'expenses.detailTitle': 'Detalle del Gasto',
  'expenses.generalInfo': 'Información General',
  'expenses.excludedParticipants': 'Participantes Excluidos',
  'expenses.expenseDivision': 'División del Gasto',
  'expenses.receipt': 'Comprobante',
  'expenses.description': 'Descripción',
  'expenses.amount': 'Monto',
  'expenses.date': 'Fecha',
  'expenses.category': 'Categoría',
  'expenses.noCategory': 'Sin categoría',
  'expenses.paidBy': 'Pagado por',
  'expenses.participants': 'participantes',
  'participant.info': 'Información del Participante',
  'summary.title': 'Resumen',
  'events.deleteTitle': 'Eliminar Evento',
  'events.deleteMessage': 'Estás seguro de que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
  'events.optionsTitle': 'Opciones del Evento',
  'events.optionsMessage': 'Selecciona una acción para "{name}"',
  'events.editEvent': 'Editar Evento',
  'events.deleteEvent': 'Eliminar Evento',
  'events.reactivate': 'Reactivar',
  'events.complete': 'Completar',
  'message.copiedToClipboard': 'copiado al portapapeles',
  'message.eventDeleted': 'Evento eliminado exitosamente',
  'message.eventDeletedError': 'Error al eliminar el evento',
  'message.eventNotEditable': 'Evento No Editable',
  'message.canOnlyAddExpensesActive': 'Solo puedes agregar gastos en eventos activos',
  'message.canOnlyEditExpensesActive': 'Solo puedes editar gastos en eventos activos',
  'message.canOnlyDeleteExpensesActive': 'Solo puedes eliminar gastos en eventos activos',
  'message.expenseDeletedSuccess': 'Gasto eliminado exitosamente',
  'message.expenseDeletedError': 'Error al eliminar el gasto',
  'message.canOnlyEditParticipantsActive': 'Solo puedes editar participantes en eventos activos',
  'message.canOnlyDeleteParticipantsActive': 'Solo puedes eliminar participantes en eventos activos',
  'message.nameRequired': 'El nombre es obligatorio',
  'message.convertedToFriend': 'Convertido a Amigo',
  'message.nowPermanentFriend': 'ahora es un amigo permanente',
  'message.updated': 'Actualizado',
  'message.participantUpdatedSuccess': 'Participante actualizado exitosamente',
  'message.participantUpdatedError': 'Error al actualizar el participante',
  'message.participantDeletedSuccess': 'Participante eliminado exitosamente',
  'message.participantDeletedError': 'Error al eliminar el participante',
  'message.paymentStateError': 'Error al cambiar el estado del pago',
  'message.receiptAdded': 'Comprobante agregado',
  'message.receiptRemoved': 'Comprobante eliminado',
  'message.receiptError': 'Error al gestionar el comprobante',
  'message.markAsComplete': 'Marcar como Completo',
  'message.markAsCompleteDesc': 'El evento se marcará como completado. Podrás gestionar pagos pero no agregar más gastos.',
  'message.markComplete': 'Completar',
  'message.eventCompleted': 'Evento Completado',
  'message.eventCompletedDesc': 'El evento ha sido marcado como completado. Puedes gestionar pagos pendientes.',
  'message.eventCompletedError': 'Error al completar el evento',
  'message.reactivateEvent': 'Reactivar Evento',
  'message.reactivateEventDesc': 'El evento volverá a estar activo y podrás agregar gastos nuevamente',
  'message.markAsCompleteShort': 'El evento está marcado como completado. Puedes gestionar pagos.',
  'message.eventReactivated': 'Evento Reactivado',
  'message.eventActiveAgain': 'El evento está activo nuevamente',
  'message.eventCompletedShort': 'El evento está marcado como completado. Puedes gestionar pagos.',
  'message.eventStateChangeError': 'Error al cambiar el estado del evento',
  'message.eventArchivedError': 'Error al archivar el evento',
  'message.participantAddedError': 'Error al agregar el participante',
  'message.receiptAddedSuccess': 'Comprobante agregado exitosamente',
  'message.receiptAddedError': 'Error al agregar el comprobante',
  // AddParticipantModal
  'addParticipant.title': 'Agregar Participantes',
  'addParticipant.tabFriends': 'Mis Amigos',
  'addParticipant.tabNew': 'Nuevo',
  'addParticipant.tabBulk': 'Masivo',
  'addParticipant.searchPlaceholder': 'Buscar en mis amigos...',
  'addParticipant.selectAll': 'Seleccionar todos',
  'addParticipant.deselectAll': 'Deseleccionar todos',
  'addParticipant.selectionCounter': '{selected} de {total}',
  'addParticipant.noFriends': 'No tienes amigos disponibles',
  'addParticipant.noFriendsDesc': 'Agrega amigos en la sección "Mis Amigos" para seleccionarlos rápidamente',
  'addParticipant.createNewParticipant': 'Crear Nuevo Participante',
  'addParticipant.selectHint': 'Toca para seleccionar amigos. Puedes elegir varios a la vez.',
  'addParticipant.noSearchResults': 'No se encontraron amigos',
  'addParticipant.noSearchResultsDesc': 'Intenta con otro término de búsqueda',
  'addParticipant.selectedCount': '{count} amigo{plural} seleccionado{pluralSelected}',
  'addParticipant.clear': 'Limpiar',
  'addParticipant.addFriend': 'Agregar Amigo',
  'addParticipant.addFriends': 'Agregar {count} Amigos',
  'addParticipant.bulkTitle': 'Agregar Participantes Masivos',
  'addParticipant.bulkSubtitle': 'Crea múltiples participantes temporales a la vez',
  'addParticipant.bulkRestricted': 'Carga Masiva Restringida',
  'addParticipant.bulkRestrictedMessage': 'Solo se pueden hacer cargas masivas de participantes cuando el evento no posee ningún gasto cargado hasta el momento.',
  'addParticipant.bulkRestrictedSuggestion': 'Puedes agregar participantes individualmente usando las pestañas "Mis Amigos" o "Nuevo".',
  'addParticipant.customNames': 'Nombres Propios',
  'addParticipant.generic': 'Genéricos',
  'addParticipant.namesLabel': 'Nombres de Participantes',
  'addParticipant.namesPlaceholder': 'Ingresa un nombre por línea:\n\nJuan Pérez\nMaría García\nCarlos López\n...',
  'addParticipant.namesHint': '💡 Escribe un nombre por línea. Sin límite de participantes.',
  'addParticipant.quantityLabel': 'Cantidad de Participantes',
  'addParticipant.genericPreview': 'Se crearán: Participante 1, Participante 2, ... Participante {count}',
  'addParticipant.genericHint': '💡 Rango: 1 a 50 participantes genéricos',
  'addParticipant.createParticipants': 'Crear Participantes',
  'addParticipant.createGeneric': 'Crear {count} Participantes',
  'addParticipant.newTitle': 'Crear Nuevo Participante',
  'addParticipant.fullNameLabel': 'Nombre Completo *',
  'addParticipant.fullNamePlaceholder': 'Nombre del participante',
  'addParticipant.cbuLabel': 'CBU/Alias (Opcional)',
  'addParticipant.cbuPlaceholder': 'Alias o CBU para pagos',
  'addParticipant.phoneLabel': 'Teléfono (Opcional)',
  'addParticipant.phonePlaceholder': '+54 9 11 1234-5678',
  'addParticipant.emailLabel': 'Email (Opcional)',
  'addParticipant.emailPlaceholder': 'correo@ejemplo.com',
  'addParticipant.saveAsFriend': 'Guardar como amigo permanente',
  'addParticipant.saveAsFriendDesc': 'Podrás reutilizar este contacto en futuros eventos',
  'addParticipant.saveAndAdd': 'Guardar Amigo y Agregar',
  'addParticipant.createAndAdd': 'Crear y Agregar',
  // AddParticipant Alerts
  'addParticipant.error.selectFriends': 'Selecciona al menos un amigo para agregar',
  'addParticipant.error.nameRequired': 'El nombre es obligatorio',
  'addParticipant.error.createParticipant': 'No se pudo crear el participante',
  'addParticipant.error.createBulk': 'No se pudieron crear los participantes',
  'addParticipant.error.atLeastOneName': 'Ingresa al menos un nombre',
  'addParticipant.error.numberRange': 'El número debe estar entre 1 y 50',
  'addParticipant.alert.bulkRestricted': '🚫 Carga Masiva Restringida',
  'addParticipant.alert.bulkRestrictedMessage': 'No se puede usar la carga masiva de participantes cuando el evento ya tiene gastos registrados.\n\nPuedes agregar participantes individualmente usando "Mis Amigos" o "Nuevo".',
  'addParticipant.alert.understood': 'Entendido',
  'addParticipant.alert.participantsAdded': '✅ Participantes Agregados',
  'addParticipant.alert.participantsAddedMessage': 'Se agregaron {count} participante{plural} correctamente',
  // ProfileScreen Privacy Section
  'profile.privacy': 'Privacidad',
  'profile.shareEmail': 'Compartir email',
  'profile.shareEmailDesc': 'Permitir que otros usuarios vean tu email',
  'profile.sharePhone': 'Compartir teléfono',
  'profile.sharePhoneDesc': 'Permitir que otros usuarios vean tu teléfono',
  'profile.allowInvitations': 'Permitir invitaciones',
  'profile.allowInvitationsDesc': 'Recibir invitaciones a eventos de otros usuarios',
  // ProfileScreen Data Section
  'profile.dataBackup': 'Datos y Respaldo',
  'profile.exportData': 'Exportar datos',
  'profile.exportDataDesc': 'Descargar una copia de tus datos',
  'profile.deleteAllData': 'Eliminar todos los datos',
  'profile.deleteAllDataDesc': 'Borrar permanentemente toda la información',
  // ProfileScreen Information Section
  'profile.information': 'Información',
  'profile.appVersion': 'Versión de la app',
  'profile.termsOfService': 'Términos de servicio',
  'profile.privacyPolicy': 'Política de privacidad',
  'profile.contactSupport': 'Contactar soporte',
  // ProfileScreen Messages
  'profile.message.selectLanguage': 'Seleccionar idioma',
  'profile.message.pickImageError': 'No se pudo seleccionar la imagen',
  'profile.message.takePhotoError': 'No se pudo tomar la foto',
  'profile.message.updateAvatarSuccess': 'Foto de perfil actualizada',
  'profile.message.updateAvatarError': 'No se pudo actualizar la foto de perfil',
  'profile.message.exportDataTitle': 'Exportar Datos',
  'profile.message.exportDataMessage': '¿Qué datos deseas exportar?',
  'profile.message.allData': 'Todos los datos',
  'profile.message.exportSuccess': 'Datos exportados correctamente',
  'profile.message.exportError': 'No se pudieron exportar los datos',
  'profile.message.deleteAllDataTitle': '⚠️ Eliminar Todos los Datos',
  'profile.message.deleteAllDataMessage': 'Esta acción eliminará permanentemente todos tus eventos, gastos y participantes. ¿Estás seguro?',
  'profile.message.deleteAll': 'Eliminar Todo',
  'profile.message.deleteCompleted': 'Todos los datos han sido eliminados',
  'profile.message.deleteError': 'No se pudieron eliminar los datos',
  'profile.message.logoutTitle': 'Cerrar Sesión',
  'profile.message.logoutMessage': '¿Estás seguro de que quieres cerrar sesión?',
  'profile.message.changeAvatarTitle': 'Cambiar foto de perfil',
  'profile.message.chooseOption': 'Elige una opción',
  'profile.message.takePhoto': 'Tomar Foto',
  'profile.message.chooseFromGallery': 'Elegir de Galería',
  'profile.message.removePhoto': 'Eliminar Foto',
  'profile.message.permissionRequired': 'Permiso requerido',
  'profile.message.galleryPermission': 'Necesitamos permiso para acceder a tus fotos',
  'profile.message.cameraPermission': 'Necesitamos permiso para acceder a tu cámara',
  'profile.message.comingSoon': 'Próximamente',
  'profile.message.userNotFound': 'No se pudo identificar el usuario',
  'profile.message.profileSaved': 'Perfil actualizado correctamente',
  'profile.message.profileSaveError': 'No se pudo guardar el perfil',
  'profile.message.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
  'profile.message.passwordChangeError': 'No se pudo cambiar la contraseña',
  'profile.message.settingUpdateError': 'No se pudo actualizar la configuración',
  'profile.message.currencySelector': 'Selector de moneda próximamente',
  'profile.message.termsComingSoon': 'Términos de servicio próximamente',
  'profile.message.privacyComingSoon': 'Política de privacidad próximamente',
  'profile.message.supportComingSoon': 'Soporte próximamente',
  // Nuevos campos ProfileScreen
  'profile.username': 'Usuario',
  'profile.shareEvent': 'Compartir Evento',
  'profile.shareEventDesc': 'Permitir que otros usuarios sean partícipes de la carga de un evento',
  'profile.importData': 'Importar datos',
  'profile.importDataDesc': 'Cargar datos desde un archivo de respaldo',
  'profile.aboutApp': 'Acerca de...',
  'profile.previousVersions': 'Versiones Anteriores',
  'profile.version': 'Versión',
  'profile.releaseNotes': 'Notas de la versión',
  'profile.bugs': 'Errores corregidos',
  'profile.improvements': 'Mejoras',
  'profile.newFeatures': 'Nuevas funcionalidades',
  // Mensajes de importación
  'profile.message.importDataTitle': 'Importar Datos',
  'profile.message.importDataMessage': 'Se reemplazarán los datos actuales',
  'profile.message.selectFile': 'Seleccionar Archivo',
  'profile.message.currentData': 'Datos actuales',
  'profile.message.newData': 'Datos a importar',
  'profile.message.importSuccess': 'Datos importados exitosamente',
  'profile.message.importError': 'Error al importar datos',
  'profile.message.aboutComingSoon': 'Información próximamente'
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string; // función de traducción con interpolación
}

// Traducciones completas embebidas (offline-first)
const translations = {
  es: {
    // General
    'app.name': 'SplitSmart',
    'welcome': 'Bienvenido',
    'login': 'Iniciar Sesión',
    'logout': 'Cerrar Sesión',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'add': 'Agregar',
    'common.add': 'Agregar',
    'edit': 'Editar',
    'delete': 'Eliminar',
    'confirm': 'Confirmar',
    'close': 'Cerrar',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'all': 'Todos',
    'yes': 'Sí',
    'no': 'No',
    'ok': 'OK',
    'error': 'Error',
    'success': 'Éxito',
    'loading': 'Cargando...',
    'noData': 'Sin datos',
    'optional': 'Opcional',
    
    // Navigation
    'home': 'Inicio',
    'events': 'Eventos',
    'expenses': 'Gastos',
    'participants': 'Participantes',
    'profile': 'Perfil',
    'settings': 'Configuración',
    'friends': 'Amigos',
    
    // Profile
    'profile.title': 'Mi Perfil',
    'profile.edit': 'Editar Perfil',
    'profile.stats': 'Estadísticas',
    'profile.activeEvents': 'Eventos Activos',
    'profile.completedEvents': 'Eventos Completados',
    'profile.archivedEvents': 'Eventos Archivados',
    'profile.friendsCount': 'Amigos',
    'profile.personalInfo': 'Información Personal',
    'profile.name': 'Nombre Completo',
    'profile.email': 'Email',
    'profile.phone': 'Teléfono',
    'profile.cbu': 'CBU/Alias',
    'profile.preferences': 'Preferencias',
    'profile.theme': 'Tema',
    'profile.themeDark': 'Oscuro',
    'profile.themeLight': 'Claro',
    'profile.currency': 'Moneda Preferida',
    'profile.language': 'Idioma',
    'profile.autoLogout': 'Cierre automático',
    'profile.autoLogoutDesc': 'Tiempo de inactividad antes de cerrar sesión',
    'profile.autoLogoutNever': 'Nunca',
    'profile.autoLogout5min': '5 minutos',
    'profile.autoLogout15min': '15 minutos',
    'profile.autoLogout30min': '30 minutos',
    'profile.notifications': 'Notificaciones',
    'profile.security': 'Seguridad',
    'profile.changePassword': 'Cambiar Contraseña',
    'profile.skipPassword': 'Ingreso sin contraseña',
    'profile.skipPasswordOn': 'No se solicitará contraseña al iniciar sesión',
    'profile.skipPasswordOff': 'Se solicitará contraseña al iniciar sesión',
    'profile.saveChanges': 'Guardar Cambios',
    'profile.newPassword': 'Nueva Contraseña',
    'profile.updatePassword': 'Actualizar Contraseña',
    'profile.passwordUpdated': '¡Contraseña actualizada!',
    'profile.passwordUpdateSuccess': 'Tu contraseña ha sido cambiada exitosamente',
    'profile.skipPasswordUpdated': '¡Actualizado!',
    'profile.skipPasswordEnabled': 'Ahora puedes ingresar solo con tu usuario o email',
    'profile.skipPasswordDisabled': 'Ahora se requerirá contraseña para ingresar',
    'profile.biometricLogin': 'Ingreso Biométrico',
    'profile.biometricLoginDesc': 'Próximamente disponible',
    'profile.comingSoon': 'Próximamente',
    'profile.autoLogout': 'Logout Automático',
    'profile.autoLogoutDesc': 'Cerrar sesión automáticamente después de inactividad',
    'profile.autoLogoutNever': 'Nunca',
    'profile.autoLogout5min': '5 minutos',
    'profile.autoLogout15min': '15 minutos',
    'profile.autoLogout30min': '30 minutos',
    'profile.selectCurrency': 'Seleccionar Moneda',
    
    // Notifications
    'notifications.expenseAdded': 'Nuevo gasto agregado',
    'notifications.expenseAddedDesc': 'Notificar cuando se agregue un gasto a tus eventos',
    'notifications.paymentReceived': 'Pago recibido',
    'notifications.paymentReceivedDesc': 'Notificar cuando recibas un pago',
    'notifications.eventUpdated': 'Evento actualizado',
    'notifications.eventUpdatedDesc': 'Notificar cuando se actualice un evento',
    'notifications.weeklyReport': 'Resumen semanal',
    'notifications.weeklyReportDesc': 'Recibir un resumen de tus gastos semanalmente',
    
    // Events
    'events.title': 'Mis Eventos',
    'events.create': 'Crear Evento',
    'events.edit': 'Editar Evento',
    'events.delete': 'Eliminar Evento',
    'events.deleteConfirm': '¿Eliminar evento?',
    'events.deleteMessage': 'Se eliminará el evento y todos sus gastos',
    'events.name': 'Nombre del Evento',
    'events.description': 'Descripción',
    'events.date': 'Fecha',
    'events.participants': 'Participantes',
    'events.addParticipant': 'Agregar Participante',
    'events.noEvents': 'No hay eventos',
    'events.noEventsDesc': 'Crea tu primer evento para comenzar',
    'events.active': 'Activo',
    'events.completed': 'Completado',
    'events.archived': 'Archivado',
    'events.finished': 'Finalizado',
    'events.summary': 'Resumen',
    'events.settlements': 'Liquidaciones',
    'events.payments': 'Pagos',
    'events.share': 'Compartir',
    'events.options': 'Opciones',
    'events.complete': 'Completar',
    'events.archive': 'Archivar',
    'events.information': 'Información del Evento',
    'events.reactivate': 'Reactivar',
    
    // Expenses
    'expenses.title': 'Gastos',
    'expenses.create': 'Crear Gasto',
    'expenses.edit': 'Editar Gasto',
    'expenses.delete': 'Eliminar Gasto',
    'expenses.deleteConfirm': '¿Eliminar gasto?',
    'expenses.deleteMessage': 'Se eliminará el gasto permanentemente',
    'expenses.description': 'Descripción del Gasto',
    'expenses.amount': 'Monto',
    'expenses.paidBy': 'Pagado por',
    'expenses.splitBetween': 'Dividido entre',
    'expenses.date': 'Fecha',
    'expenses.category': 'Categoría',
    'expenses.noExpenses': 'No hay gastos',
    'expenses.noExpensesDesc': 'Agrega tu primer gasto',
    'expenses.total': 'Total',
    'expenses.division': 'División',
    'expenses.selectAll': 'Seleccionar Todos',
    'expenses.equally': 'Dividir Equitativamente',
    'expenses.custom': 'División Personalizada',
    'expenses.saved': 'Gasto guardado',
    'expenses.search': 'Buscar gastos...',
    'expenses.byParticipant': 'Gastos por Participante',
    'expenses.byCategory': 'Gastos por Categoría',
    'expenses.filters': 'Filtros',
    'expenses.filterBy': 'Filtrar por',
    'expenses.sortBy': 'Ordenar por',
    'expenses.category': 'Categoría',
    'expenses.payer': 'Pagador',
    'expenses.amount': 'Monto',
    'expenses.date': 'Fecha',
    'expenses.description': 'Descripción',
    'expenses.all': 'Todos',
    'expenses.clearFilters': 'Limpiar Filtros',
    
    // Participants
    'participants.title': 'Participantes',
    'participants.add': 'Agregar Participante',
    'participants.select': 'Seleccionar Participante',
    'participants.noParticipants': 'No hay participantes',
    'participants.noParticipantsDesc': 'Agrega participantes para comenzar',
    'participants.name': 'Nombre',
    'participants.email': 'Email',
    'participants.phone': 'Teléfono',
    'participants.balance': 'Balance',
    'participants.owes': 'Debe',
    'participants.owed': 'Le deben',
    'participants.search': 'Buscar participantes...',
    
    // Friends
    'friends.title': 'Mis Amigos',
    'friends.add': 'Agregar Amigo',
    'friends.edit': 'Editar Amigo',
    'friends.delete': 'Eliminar Amigo',
    'friends.deleteConfirm': '¿Eliminar amigo?',
    'friends.deleteMessage': 'Se eliminará el amigo de tu lista',
    'friends.noFriends': 'No hay amigos',
    'friends.noFriendsDesc': 'Agrega amigos para facilitar la creación de eventos',
    'friends.saved': 'Amigo guardado',
    
    // Payments
    'payments.title': 'Pagos',
    'payments.record': 'Registrar Pago',
    'payments.markAsPaid': 'Marcar como Pagado',
    'payments.paid': 'PAGADO',
    'payments.pending': 'Pendiente',
    'payments.confirmed': 'Confirmado',
    'payments.from': 'De',
    'payments.to': 'Para',
    'payments.amount': 'Monto',
    'payments.date': 'Fecha',
    'payments.confirmPayment': 'Confirmar Pago',
    'payments.confirmMessage': '¿Marcar este pago como realizado?',
    'payments.recorded': 'Pago registrado',
    
    // Summary
    'summary.title': 'Resumen',
    'summary.totalSpent': 'Total Gastado',
    'summary.yourShare': 'Tu Parte',
    'summary.balance': 'Balance',
    'summary.settlements': 'Liquidaciones',
    'summary.youOwe': 'Debes',
    'summary.owesYou': 'Te debe',
    'summary.settled': 'Liquidado',
    'summary.shareViaWhatsApp': 'Compartir por WhatsApp',
    
    // Categories
    'category.food': 'Comida',
    'category.transport': 'Transporte',
    'category.accommodation': 'Alojamiento',
    'category.entertainment': 'Entretenimiento',
    'category.shopping': 'Compras',
    'category.other': 'Otro',
    
    // Messages
    'message.selectLanguage': 'Seleccionar Idioma',
    'message.eventNotEditable': 'Evento No Editable',
    'message.canOnlyAddExpensesActive': 'Solo puedes agregar gastos en eventos activos',
    'message.canOnlyEditExpensesActive': 'Solo puedes editar gastos en eventos activos',
    'message.canOnlyDeleteExpensesActive': 'Solo puedes eliminar gastos en eventos activos',
    'message.canOnlyEditParticipantsActive': 'Solo puedes editar participantes en eventos activos',
    'message.canOnlyDeleteParticipantsActive': 'Solo puedes eliminar participantes en eventos activos',
    'message.nameRequired': 'El nombre es obligatorio',
    'message.expenseDeletedSuccess': 'Gasto eliminado correctamente',
    'message.expenseDeletedError': 'No se pudo eliminar el gasto',
    'message.participantUpdatedSuccess': 'Participante actualizado correctamente',
    'message.participantUpdatedError': 'No se pudo actualizar el participante',
    'message.participantDeletedSuccess': 'Participante eliminado correctamente',
    'message.participantDeletedError': 'No se pudo eliminar el participante',
    'message.convertedToFriend': 'Convertido a Amigo',
    'message.nowPermanentFriend': 'ahora es un amigo permanente y aparecerá en "Mis Amigos"',
    'message.updated': 'Actualizado',
    'message.paymentStateError': 'No se pudo actualizar el estado del pago',
    'message.receiptAdded': 'Comprobante agregado',
    'message.receiptRemoved': 'Comprobante eliminado',
    'message.receiptError': 'No se pudo actualizar el comprobante',
    'message.eventCompleted': 'Evento Completo',
    'message.eventCompletedDesc': 'El evento está marcado como completo. Puedes gestionar los pagos.',
    'message.eventCompletedError': 'No se pudo completar el evento',
    'message.eventArchived': 'Evento Archivado',
    'message.eventArchivedDesc': 'El evento ha sido archivado correctamente',
    'message.eventArchivedError': 'No se pudo archivar el evento',
    'message.expenseAdded': 'Gasto agregado',
    'message.expenseAddedDesc': 'El gasto se agregó correctamente',
    'message.participantAdded': 'Participante agregado',
    'message.participantAddedDesc': 'se agregó al evento',
    'message.participantAddedError': 'No se pudo agregar el participante',
    'message.receiptAddedSuccess': 'Comprobante agregado correctamente',
    'message.receiptAddedError': 'No se pudo agregar el comprobante',
    'message.noSettlements': 'Sin liquidaciones',
    'message.noSettlementsDesc': 'No hay liquidaciones pendientes para crear pagos',
    'message.whatsappNotAvailable': 'WhatsApp no disponible',
    'message.copiedToClipboard': 'se copió al portapapeles. Puedes pegarlo en cualquier aplicación.',
    'message.whatsappError': 'Error al abrir WhatsApp',
    'message.eventStateChangeError': 'No se pudo cambiar el estado del evento',
    'message.eventDeletedError': 'No se pudo eliminar el evento',
    'message.markAsComplete': 'Marcar como Completo',
    'message.markAsCompleteDesc': 'Al marcar el evento como completo se bloquearán los gastos y participantes, pero podrás gestionar los pagos de liquidación.\n\n¿Deseas continuar?',
    'message.markComplete': 'Marcar Completo',
    'message.reactivateEvent': 'Reactivar Evento',
    'message.reactivateEventDesc': '¿Deseas reactivar el evento? Podrás volver a editar gastos y participantes.',
    'message.markAsCompleteShort': '¿Deseas marcar el evento como completo? Se bloquearán los gastos y participantes, pero podrás gestionar pagos.',
    'message.eventReactivated': 'Evento Reactivado',
    'message.eventActiveAgain': 'El evento está activo nuevamente',
    'message.eventCompletedShort': 'El evento está marcado como completo. Puedes gestionar los pagos.',
    'message.archiveEvent': 'Archivar Evento',
    'message.archiveEventDesc': 'El evento archivado solo será visible en el historial. Puedes reactivarlo cuando quieras.',
    'common.success': 'Éxito',
    'message.paymentsCreated': 'pago creado correctamente',
    'message.paymentsCreatedPlural': 'pagos creados correctamente',
    'message.eventDeleted': 'Evento eliminado correctamente',
    'message.enterExpenseDescription': 'Ingresa la descripción del gasto:',
    'message.paymentFromSettlement': 'Pago creado desde liquidación',
    'message.couldNotCreatePayments': 'No se pudieron crear los pagos',
    'settlement.addReceipt': 'Agregar Comprobante',
    'settlement.chooseOption': 'Elige una opción',
    'settlement.takePhoto': 'Tomar Foto',
    'settlement.chooseFromGallery': 'Elegir de Galería',
    'settlement.deleteReceipt': 'Eliminar Comprobante',
    'settlement.permissionRequired': 'Permiso requerido',
    'settlement.galleryPermissionDesc': 'Para seleccionar una imagen de la galería, necesitamos permisos de acceso. Por favor, habilita los permisos en la configuración de la app.',
    'settlement.openSettings': 'Abrir Configuración',
    'settlement.galleryError': 'No se pudo abrir la galería. Inténtalo de nuevo.',
    'settlement.permissionDenied': 'Permiso denegado',
    'settlement.cameraPermissionDesc': 'Necesitamos acceso a la cámara',
    'participant.info': 'Información del Participante',
    'expenses.title': 'Gastos',
    'expenses.paidBy': 'Pagado por',
    'expenses.division': 'División',
    'expenses.excluded': 'Excluidos',
    'expenses.edit': 'Editar',
    'expenses.delete': 'Eliminar',
    'expenses.noExpenses': 'No hay gastos registrados',
    'expenses.noExpensesDesc': 'Toca "Agregar" para crear el primer gasto',
    'expenses.noResults': 'No se encontraron gastos',
    'expenses.noResultsDesc': 'Intenta con otros filtros o búsqueda',
    'receipt.label': 'Comprobante',
    'message.chooseLanguage': 'Elige tu idioma preferido',
    'message.noParticipantsSelected': 'Selecciona al menos un participante',
    'message.fillAllFields': 'Completa todos los campos requeridos',
    'message.invalidAmount': 'Ingresa un monto válido',
    'message.eventCreated': 'Evento creado exitosamente',
    'message.eventUpdated': 'Evento actualizado',
    'message.expenseCreated': 'Gasto creado exitosamente',
    'message.expenseUpdated': 'Gasto actualizado',
    'message.confirmDelete': 'Confirmar eliminación',
    
    // Traducciones adicionales específicas
    'common.add': 'Agregar',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.cancel': 'Cancelar',
    'participants.title': 'Participantes',
    'participants.search': 'Buscar participantes...',
    'participants.noParticipants': 'No hay participantes',
    'participants.noParticipantsDesc': 'Agrega participantes para dividir los gastos',
    'participants.balance': 'Balance',
    'participants.owes': 'Se le debe',
    'participants.shouldPay': 'Debe pagar',
    'participants.balanced': 'Equilibrado',
    'participants.contactInfo': 'Información de Contacto',
    'participants.additionalInfo': 'Información Adicional',
    'participants.addedToEvent': 'Agregado al evento',
    'participants.noContactInfo': 'No hay información de contacto disponible',
    'participants.friendPermanent': 'Amigo Permanente',
    'participants.temporaryParticipant': 'Participante Temporal',
    'participant.info': 'Información del Participante',
    'expenses.detailTitle': 'Detalle del Gasto',
    'expenses.generalInfo': 'Información General',
    'expenses.excludedParticipants': 'Participantes Excluidos',
    'expenses.expenseDivision': 'División del Gasto',
    'expenses.receipt': 'Comprobante',
    'expenses.description': 'Descripción',
    'expenses.amount': 'Monto',
    'expenses.date': 'Fecha',
    'expenses.category': 'Categoría',
    'expenses.noCategory': 'Sin categoría',
    'expenses.paidBy': 'Pagado por',
    'expenses.participants': 'participantes',
    'summary.title': 'Resumen',
  },
  en: {
    // General
    'app.name': 'SplitSmart',
    'welcome': 'Welcome',
    'login': 'Sign In',
    'logout': 'Sign Out',
    'cancel': 'Cancel',
    'save': 'Save',
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'close': 'Close',
    'search': 'Search',
    'filter': 'Filter',
    'all': 'All',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'error': 'Error',
    'success': 'Success',
    'loading': 'Loading...',
    'noData': 'No data',
    'optional': 'Optional',
    
    // Navigation
    'home': 'Home',
    'events': 'Events',
    'expenses': 'Expenses',
    'participants': 'Participants',
    'profile': 'Profile',
    'settings': 'Settings',
    'friends': 'Friends',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.edit': 'Edit Profile',
    'profile.stats': 'Statistics',
    'profile.activeEvents': 'Active Events',
    'profile.completedEvents': 'Completed Events',
    'profile.archivedEvents': 'Archived Events',
    'profile.friendsCount': 'Friends',
    'profile.personalInfo': 'Personal Information',
    'profile.name': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.cbu': 'Bank Account',
    'profile.preferences': 'Preferences',
    'profile.theme': 'Theme',
    'profile.themeDark': 'Dark',
    'profile.themeLight': 'Light',
    'profile.currency': 'Preferred Currency',
    'profile.language': 'Language',
    'profile.autoLogout': 'Auto Logout',
    'profile.autoLogoutDesc': 'Inactivity time before logout',
    'profile.autoLogoutNever': 'Never',
    'profile.autoLogout5min': '5 minutes',
    'profile.autoLogout15min': '15 minutes',
    'profile.autoLogout30min': '30 minutes',
    'profile.notifications': 'Notifications',
    'profile.security': 'Security',
    'profile.changePassword': 'Change Password',
    'profile.skipPassword': 'Login without password',
    'profile.skipPasswordOn': 'Password will not be required at login',
    'profile.skipPasswordOff': 'Password will be required at login',
    'profile.saveChanges': 'Save Changes',
    'profile.newPassword': 'New Password',
    'profile.updatePassword': 'Update Password',
    'profile.passwordUpdated': 'Password updated!',
    'profile.passwordUpdateSuccess': 'Your password has been changed successfully',
    'profile.skipPasswordUpdated': 'Updated!',
    'profile.skipPasswordEnabled': 'You can now login with just your username or email',
    'profile.skipPasswordDisabled': 'Password will now be required to login',
    'profile.biometricLogin': 'Biometric Login',
    'profile.biometricLoginDesc': 'Coming soon',
    'profile.comingSoon': 'Coming Soon',
    'profile.autoLogout': 'Auto Logout',
    'profile.autoLogoutDesc': 'Automatically sign out after inactivity',
    'profile.autoLogoutNever': 'Never',
    'profile.autoLogout5min': '5 minutes',
    'profile.autoLogout15min': '15 minutes',
    'profile.autoLogout30min': '30 minutes',
    'profile.selectCurrency': 'Select Currency',
    
    // Notifications
    'notifications.expenseAdded': 'New expense added',
    'notifications.expenseAddedDesc': 'Notify when an expense is added to your events',
    'notifications.paymentReceived': 'Payment received',
    'notifications.paymentReceivedDesc': 'Notify when you receive a payment',
    'notifications.eventUpdated': 'Event updated',
    'notifications.eventUpdatedDesc': 'Notify when an event is updated',
    'notifications.weeklyReport': 'Weekly summary',
    'notifications.weeklyReportDesc': 'Receive a summary of your expenses weekly',
    
    // Events
    'events.title': 'My Events',
    'events.create': 'Create Event',
    'events.edit': 'Edit Event',
    'events.delete': 'Delete Event',
    'events.deleteConfirm': 'Delete event?',
    'events.deleteMessage': 'This will delete the event and all its expenses',
    'events.name': 'Event Name',
    'events.description': 'Description',
    'events.date': 'Date',
    'events.participants': 'Participants',
    'events.addParticipant': 'Add Participant',
    'events.noEvents': 'No events',
    'events.noEventsDesc': 'Create your first event to get started',
    'events.active': 'Active',
    'events.completed': 'Completed',
    'events.archived': 'Archived',
    'events.finished': 'Finished',
    'events.summary': 'Summary',
    'events.settlements': 'Settlements',
    'events.payments': 'Payments',
    'events.share': 'Share',
    'events.options': 'Options',
    'events.complete': 'Complete',
    'events.archive': 'Archive',
    'events.information': 'Event Information',
    'events.reactivate': 'Reactivate',
    
    // Expenses
    'expenses.title': 'Expenses',
    'expenses.create': 'Create Expense',
    'expenses.edit': 'Edit Expense',
    'expenses.delete': 'Delete Expense',
    'expenses.deleteConfirm': 'Delete expense?',
    'expenses.deleteMessage': 'This will permanently delete the expense',
    'expenses.description': 'Expense Description',
    'expenses.amount': 'Amount',
    'expenses.paidBy': 'Paid by',
    'expenses.splitBetween': 'Split between',
    'expenses.date': 'Date',
    'expenses.category': 'Category',
    'expenses.noExpenses': 'No expenses',
    'expenses.noExpensesDesc': 'Add your first expense',
    'expenses.total': 'Total',
    'expenses.division': 'Division',
    'expenses.selectAll': 'Select All',
    'expenses.equally': 'Split Equally',
    'expenses.custom': 'Custom Split',
    'expenses.saved': 'Expense saved',
    'expenses.search': 'Search expenses...',
    'expenses.byParticipant': 'Expenses by Participant',
    'expenses.byCategory': 'Expenses by Category',
    'expenses.filters': 'Filters',
    'expenses.filterBy': 'Filter by',
    'expenses.sortBy': 'Sort by',
    'expenses.category': 'Category',
    'expenses.payer': 'Payer',
    'expenses.amount': 'Amount',
    'expenses.date': 'Date',
    'expenses.description': 'Description',
    'expenses.all': 'All',
    'expenses.clearFilters': 'Clear Filters',
    
    // Participants
    'participants.title': 'Participants',
    'participants.add': 'Add Participant',
    'participants.select': 'Select Participant',
    'participants.noParticipants': 'No participants',
    'participants.noParticipantsDesc': 'Add participants to get started',
    'participants.name': 'Name',
    'participants.email': 'Email',
    'participants.phone': 'Phone',
    'participants.balance': 'Balance',
    'participants.owes': 'Owes',
    'participants.owed': 'Is owed',
    'participants.search': 'Search participants...',
    
    // Friends
    'friends.title': 'My Friends',
    'friends.add': 'Add Friend',
    'friends.edit': 'Edit Friend',
    'friends.delete': 'Delete Friend',
    'friends.deleteConfirm': 'Delete friend?',
    'friends.deleteMessage': 'This will remove the friend from your list',
    'friends.noFriends': 'No friends',
    'friends.noFriendsDesc': 'Add friends to make event creation easier',
    'friends.saved': 'Friend saved',
    
    // Payments
    'payments.title': 'Payments',
    'payments.record': 'Record Payment',
    'payments.markAsPaid': 'Mark as Paid',
    'payments.paid': 'PAID',
    'payments.pending': 'Pending',
    'payments.confirmed': 'Confirmed',
    'payments.from': 'From',
    'payments.to': 'To',
    'payments.amount': 'Amount',
    'payments.date': 'Date',
    'payments.confirmPayment': 'Confirm Payment',
    'payments.confirmMessage': 'Mark this payment as completed?',
    'payments.recorded': 'Payment recorded',
    
    // Summary
    'summary.title': 'Summary',
    'summary.totalSpent': 'Total Spent',
    'summary.yourShare': 'Your Share',
    'summary.balance': 'Balance',
    'summary.settlements': 'Settlements',
    'summary.youOwe': 'You owe',
    'summary.owesYou': 'Owes you',
    'summary.settled': 'Settled',
    'summary.shareViaWhatsApp': 'Share via WhatsApp',
    
    // Categories
    'category.food': 'Food',
    'category.transport': 'Transport',
    'category.accommodation': 'Accommodation',
    'category.entertainment': 'Entertainment',
    'category.shopping': 'Shopping',
    'category.other': 'Other',
    
    // Messages
    'message.selectLanguage': 'Select Language',
    'message.eventNotEditable': 'Event Not Editable',
    'message.canOnlyAddExpensesActive': 'You can only add expenses to active events',
    'message.canOnlyEditExpensesActive': 'You can only edit expenses in active events',
    'message.canOnlyDeleteExpensesActive': 'You can only delete expenses in active events',
    'message.canOnlyEditParticipantsActive': 'You can only edit participants in active events',
    'message.canOnlyDeleteParticipantsActive': 'You can only delete participants in active events',
    'message.nameRequired': 'Name is required',
    'message.expenseDeletedSuccess': 'Expense deleted successfully',
    'message.expenseDeletedError': 'Could not delete expense',
    'message.participantUpdatedSuccess': 'Participant updated successfully',
    'message.participantUpdatedError': 'Could not update participant',
    'message.participantDeletedSuccess': 'Participant deleted successfully',
    'message.participantDeletedError': 'Could not delete participant',
    'message.convertedToFriend': 'Converted to Friend',
    'message.nowPermanentFriend': 'is now a permanent friend and will appear in \"My Friends\"',
    'message.updated': 'Updated',
    'message.paymentStateError': 'Could not update payment status',
    'message.receiptAdded': 'Receipt added',
    'message.receiptRemoved': 'Receipt removed',
    'message.receiptError': 'Could not update receipt',
    'message.eventCompleted': 'Event Completed',
    'message.eventCompletedDesc': 'The event is marked as completed. You can manage payments.',
    'message.eventCompletedError': 'Could not complete event',
    'message.eventArchived': 'Event Archived',
    'message.eventArchivedDesc': 'The event has been archived successfully',
    'message.eventArchivedError': 'Could not archive event',
    'message.expenseAdded': 'Expense added',
    'message.expenseAddedDesc': 'The expense was added successfully',
    'message.participantAdded': 'Participant added',
    'message.participantAddedDesc': 'was added to the event',
    'message.participantAddedError': 'Could not add participant',
    'message.receiptAddedSuccess': 'Receipt added successfully',
    'message.receiptAddedError': 'Could not add receipt',
    'message.noSettlements': 'No settlements',
    'message.noSettlementsDesc': 'There are no pending settlements to create payments',
    'message.whatsappNotAvailable': 'WhatsApp not available',
    'message.copiedToClipboard': 'was copied to clipboard. You can paste it in any app.',
    'message.whatsappError': 'Error opening WhatsApp',
    'message.eventStateChangeError': 'Could not change event status',
    'message.eventDeletedError': 'Could not delete event',
    'message.markAsComplete': 'Mark as Complete',
    'message.markAsCompleteDesc': 'Marking the event as complete will lock expenses and participants, but you can manage settlement payments.\n\nDo you want to continue?',
    'message.markComplete': 'Mark Complete',
    'message.reactivateEvent': 'Reactivate Event',
    'message.reactivateEventDesc': 'Do you want to reactivate the event? You will be able to edit expenses and participants again.',
    'message.markAsCompleteShort': 'Do you want to mark the event as complete? Expenses and participants will be locked, but you can manage payments.',
    'message.eventReactivated': 'Event Reactivated',
    'message.eventActiveAgain': 'The event is active again',
    'message.eventCompletedShort': 'The event is marked as complete. You can manage payments.',
    'message.archiveEvent': 'Archive Event',
    'message.archiveEventDesc': 'The archived event will only be visible in history. You can reactivate it whenever you want.',
    'common.success': 'Success',
    'message.paymentsCreated': 'payment created successfully',
    'message.paymentsCreatedPlural': 'payments created successfully',
    'message.eventDeleted': 'Event deleted successfully',
    'message.enterExpenseDescription': 'Enter the expense description:',
    'message.paymentFromSettlement': 'Payment created from settlement',
    'message.couldNotCreatePayments': 'Could not create payments',
    'settlement.addReceipt': 'Add Receipt',
    'settlement.chooseOption': 'Choose an option',
    'settlement.takePhoto': 'Take Photo',
    'settlement.chooseFromGallery': 'Choose from Gallery',
    'settlement.deleteReceipt': 'Delete Receipt',
    'settlement.permissionRequired': 'Permission required',
    'settlement.galleryPermissionDesc': 'To select an image from the gallery, we need access permissions. Please enable permissions in app settings.',
    'settlement.openSettings': 'Open Settings',
    'settlement.galleryError': 'Could not open gallery. Please try again.',
    'settlement.permissionDenied': 'Permission denied',
    'settlement.cameraPermissionDesc': 'We need camera access',
    'participant.info': 'Participant Information',
    'expenses.title': 'Expenses',
    'expenses.paidBy': 'Paid by',
    'expenses.division': 'Division',
    'expenses.excluded': 'Excluded',
    'expenses.edit': 'Edit',
    'expenses.delete': 'Delete',
    'expenses.noExpenses': 'No expenses recorded',
    'expenses.noExpensesDesc': 'Tap "Add" to create the first expense',
    'expenses.noResults': 'No expenses found',
    'expenses.noResultsDesc': 'Try with other filters or search',
    'receipt.label': 'Receipt',
    'message.chooseLanguage': 'Choose your preferred language',
    'message.noParticipantsSelected': 'Select at least one participant',
    'message.fillAllFields': 'Fill in all required fields',
    'message.invalidAmount': 'Enter a valid amount',
    'message.eventCreated': 'Event created successfully',
    'message.eventUpdated': 'Event updated',
    'message.expenseCreated': 'Expense created successfully',
    'message.expenseUpdated': 'Expense updated',
    'message.confirmDelete': 'Confirm deletion',
    
    // Additional translations for English
    'common.add': 'Add',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.cancel': 'Cancel',
    'participants.title': 'Participants',
    'participants.search': 'Search participants...',
    'participants.noParticipants': 'No participants',
    'participants.noParticipantsDesc': 'Add participants to split expenses',
    'participants.balance': 'Balance',
    'participants.owes': 'Owed',
    'participants.shouldPay': 'Should pay',
    'participants.balanced': 'Balanced',
    'participants.contactInfo': 'Contact Information',
    'participants.additionalInfo': 'Additional Information',
    'participants.addedToEvent': 'Added to event',
    'participants.noContactInfo': 'No contact information available',
    'participants.friendPermanent': 'Permanent Friend',
    'participants.temporaryParticipant': 'Temporary Participant',
    'participant.info': 'Participant Information',
    'expenses.detailTitle': 'Expense Detail',
    'expenses.generalInfo': 'General Information',
    'expenses.excludedParticipants': 'Excluded Participants',
    'expenses.expenseDivision': 'Expense Division',
    'expenses.receipt': 'Receipt',
    'expenses.description': 'Description',
    'expenses.amount': 'Amount',
    'expenses.date': 'Date',
    'expenses.category': 'Category',
    'expenses.noCategory': 'No category',
    'expenses.paidBy': 'Paid by',
    'expenses.participants': 'participants',
    'summary.title': 'Summary',
    // AddParticipantModal
    'addParticipant.title': 'Add Participants',
    'addParticipant.tabFriends': 'My Friends',
    'addParticipant.tabNew': 'New',
    'addParticipant.tabBulk': 'Bulk',
    'addParticipant.searchPlaceholder': 'Search friends...',
    'addParticipant.selectAll': 'Select all',
    'addParticipant.deselectAll': 'Deselect all',
    'addParticipant.selectionCounter': '{selected} of {total}',
    'addParticipant.noFriends': 'No friends available',
    'addParticipant.noFriendsDesc': 'Add friends in the "My Friends" section to select them quickly',
    'addParticipant.createNewParticipant': 'Create New Participant',
    'addParticipant.selectHint': 'Tap to select friends. You can choose multiple at once.',
    'addParticipant.noSearchResults': 'No friends found',
    'addParticipant.noSearchResultsDesc': 'Try another search term',
    'addParticipant.selectedCount': '{count} friend{plural} selected',
    'addParticipant.clear': 'Clear',
    'addParticipant.addFriend': 'Add Friend',
    'addParticipant.addFriends': 'Add {count} Friends',
    'addParticipant.bulkTitle': 'Add Bulk Participants',
    'addParticipant.bulkSubtitle': 'Create multiple temporary participants at once',
    'addParticipant.bulkRestricted': 'Bulk Load Restricted',
    'addParticipant.bulkRestrictedMessage': 'Bulk participant loading can only be done when the event has no recorded expenses.',
    'addParticipant.bulkRestrictedSuggestion': 'You can add participants individually using the "My Friends" or "New" tabs.',
    'addParticipant.customNames': 'Custom Names',
    'addParticipant.generic': 'Generic',
    'addParticipant.namesLabel': 'Participant Names',
    'addParticipant.namesPlaceholder': 'Enter one name per line:\n\nJohn Doe\nMary Smith\nCarlos Lopez\n...',
    'addParticipant.namesHint': '💡 Write one name per line. No limit on participants.',
    'addParticipant.quantityLabel': 'Number of Participants',
    'addParticipant.genericPreview': 'Will create: Participant 1, Participant 2, ... Participant {count}',
    'addParticipant.genericHint': '💡 Range: 1 to 50 generic participants',
    'addParticipant.createParticipants': 'Create Participants',
    'addParticipant.createGeneric': 'Create {count} Participants',
    'addParticipant.newTitle': 'Create New Participant',
    'addParticipant.fullNameLabel': 'Full Name *',
    'addParticipant.fullNamePlaceholder': 'Participant name',
    'addParticipant.cbuLabel': 'Bank Account/Alias (Optional)',
    'addParticipant.cbuPlaceholder': 'Alias or bank account for payments',
    'addParticipant.phoneLabel': 'Phone (Optional)',
    'addParticipant.phonePlaceholder': '+1 555 123-4567',
    'addParticipant.emailLabel': 'Email (Optional)',
    'addParticipant.emailPlaceholder': 'email@example.com',
    'addParticipant.saveAsFriend': 'Save as permanent friend',
    'addParticipant.saveAsFriendDesc': 'You can reuse this contact in future events',
    'addParticipant.saveAndAdd': 'Save Friend and Add',
    'addParticipant.createAndAdd': 'Create and Add',
    // AddParticipant Alerts
    'addParticipant.error.selectFriends': 'Select at least one friend to add',
    'addParticipant.error.nameRequired': 'Name is required',
    'addParticipant.error.createParticipant': 'Could not create participant',
    'addParticipant.error.createBulk': 'Could not create participants',
    'addParticipant.error.atLeastOneName': 'Enter at least one name',
    'addParticipant.error.numberRange': 'Number must be between 1 and 50',
    'addParticipant.alert.bulkRestricted': '🚫 Bulk Load Restricted',
    'addParticipant.alert.bulkRestrictedMessage': 'Bulk participant loading cannot be used when the event already has recorded expenses.\n\nYou can add participants individually using "My Friends" or "New".',
    'addParticipant.alert.understood': 'Understood',
    'addParticipant.alert.participantsAdded': '✅ Participants Added',
    'addParticipant.alert.participantsAddedMessage': '{count} participant{plural} added successfully',
    // ProfileScreen Privacy Section
    'profile.privacy': 'Privacy',
    'profile.shareEmail': 'Share email',
    'profile.shareEmailDesc': 'Allow other users to see your email',
    'profile.sharePhone': 'Share phone',
    'profile.sharePhoneDesc': 'Allow other users to see your phone',
    'profile.allowInvitations': 'Allow invitations',
    'profile.allowInvitationsDesc': 'Receive event invitations from other users',
    // ProfileScreen Data Section
    'profile.dataBackup': 'Data & Backup',
    'profile.exportData': 'Export data',
    'profile.exportDataDesc': 'Download a copy of your data',
    'profile.deleteAllData': 'Delete all data',
    'profile.deleteAllDataDesc': 'Permanently delete all information',
    // ProfileScreen Information Section
    'profile.information': 'Information',
    'profile.appVersion': 'App version',
    'profile.termsOfService': 'Terms of service',
    'profile.privacyPolicy': 'Privacy policy',
    'profile.contactSupport': 'Contact support',
    // ProfileScreen Messages
    'profile.message.selectLanguage': 'Select language',
    'profile.message.pickImageError': 'Could not select image',
    'profile.message.takePhotoError': 'Could not take photo',
    'profile.message.updateAvatarSuccess': 'Profile photo updated',
    'profile.message.updateAvatarError': 'Could not update profile photo',
    'profile.message.exportDataTitle': 'Export Data',
    'profile.message.exportDataMessage': 'What data do you want to export?',
    'profile.message.allData': 'All data',
    'profile.message.exportSuccess': 'Data exported successfully',
    'profile.message.exportError': 'Could not export data',
    'profile.message.deleteAllDataTitle': '⚠️ Delete All Data',
    'profile.message.deleteAllDataMessage': 'This action will permanently delete all your events, expenses and participants. Are you sure?',
    'profile.message.deleteAll': 'Delete All',
    'profile.message.deleteCompleted': 'All data has been deleted',
    'profile.message.deleteError': 'Could not delete data',
    'profile.message.logoutTitle': 'Sign Out',
    'profile.message.logoutMessage': 'Are you sure you want to sign out?',
    'profile.message.changeAvatarTitle': 'Change profile photo',
    'profile.message.chooseOption': 'Choose an option',
    'profile.message.takePhoto': 'Take Photo',
    'profile.message.chooseFromGallery': 'Choose from Gallery',
    'profile.message.removePhoto': 'Remove Photo',
    'profile.message.permissionRequired': 'Permission required',
    'profile.message.galleryPermission': 'We need permission to access your photos',
    'profile.message.cameraPermission': 'We need permission to access your camera',
    'profile.message.comingSoon': 'Coming soon',
    'profile.message.userNotFound': 'Could not identify user',
    'profile.message.profileSaved': 'Profile updated successfully',
    'profile.message.profileSaveError': 'Could not save profile',
    'profile.message.passwordTooShort': 'Password must be at least 6 characters',
    'profile.message.passwordChangeError': 'Could not change password',
    'profile.message.settingUpdateError': 'Could not update setting',
    'profile.message.currencySelector': 'Currency selector coming soon',
    'profile.message.termsComingSoon': 'Terms of service coming soon',
    'profile.message.privacyComingSoon': 'Privacy policy coming soon',
    'profile.message.supportComingSoon': 'Support coming soon',
    // New ProfileScreen fields
    'profile.username': 'Username',
    'profile.shareEvent': 'Share Event',
    'profile.shareEventDesc': 'Allow other users to participate in event loading',
    'profile.importData': 'Import data',
    'profile.importDataDesc': 'Load data from a backup file',
    'profile.aboutApp': 'About...',
    'profile.previousVersions': 'Previous Versions',
    'profile.version': 'Version',
    'profile.releaseNotes': 'Release notes',
    'profile.bugs': 'Bug fixes',
    'profile.improvements': 'Improvements',
    'profile.newFeatures': 'New features',
    // Import messages
    'profile.message.importDataTitle': 'Import Data',
    'profile.message.importDataMessage': 'Current data will be replaced',
    'profile.message.selectFile': 'Select File',
    'profile.message.currentData': 'Current data',
    'profile.message.newData': 'Data to import',
    'profile.message.importSuccess': 'Data imported successfully',
    'profile.message.importError': 'Error importing data',
    'profile.message.aboutComingSoon': 'Information coming soon'
  },
  pt: {
    // General
    'app.name': 'SplitSmart',
    'welcome': 'Bem-vindo',
    'login': 'Entrar',
    'logout': 'Sair',
    'cancel': 'Cancelar',
    'save': 'Salvar',
    'add': 'Adicionar',
    'edit': 'Editar',
    'delete': 'Excluir',
    'confirm': 'Confirmar',
    'close': 'Fechar',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'all': 'Todos',
    'yes': 'Sim',
    'no': 'Não',
    'ok': 'OK',
    'error': 'Erro',
    'success': 'Sucesso',
    'loading': 'Carregando...',
    'noData': 'Sem dados',
    'optional': 'Opcional',
    
    // Navigation
    'home': 'Início',
    'events': 'Eventos',
    'expenses': 'Despesas',
    'participants': 'Participantes',
    'profile': 'Perfil',
    'settings': 'Configurações',
    'friends': 'Amigos',
    
    // Profile
    'profile.title': 'Meu Perfil',
    'profile.edit': 'Editar Perfil',
    'profile.stats': 'Estatísticas',
    'profile.activeEvents': 'Eventos Ativos',
    'profile.completedEvents': 'Eventos Concluídos',
    'profile.archivedEvents': 'Eventos Arquivados',
    'profile.friendsCount': 'Amigos',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.name': 'Nome Completo',
    'profile.email': 'Email',
    'profile.phone': 'Telefone',
    'profile.cbu': 'Conta Bancária',
    'profile.preferences': 'Preferências',
    'profile.theme': 'Tema',
    'profile.themeDark': 'Escuro',
    'profile.themeLight': 'Claro',
    'profile.currency': 'Moeda Preferida',
    'profile.language': 'Idioma',
    'profile.autoLogout': 'Logout automático',
    'profile.autoLogoutDesc': 'Tempo de inatividade antes do logout',
    'profile.autoLogoutNever': 'Nunca',
    'profile.autoLogout5min': '5 minutos',
    'profile.autoLogout15min': '15 minutos',
    'profile.autoLogout30min': '30 minutos',
    'profile.notifications': 'Notificações',
    'profile.security': 'Segurança',
    'profile.changePassword': 'Alterar Senha',
    'profile.skipPassword': 'Login sem senha',
    'profile.skipPasswordOn': 'Senha não será solicitada no login',
    'profile.skipPasswordOff': 'Senha será solicitada no login',
    'profile.saveChanges': 'Salvar Alterações',
    'profile.newPassword': 'Nova Senha',
    'profile.updatePassword': 'Atualizar Senha',
    'profile.passwordUpdated': 'Senha atualizada!',
    'profile.passwordUpdateSuccess': 'Sua senha foi alterada com sucesso',
    'profile.skipPasswordUpdated': 'Atualizado!',
    'profile.skipPasswordEnabled': 'Agora você pode entrar apenas com seu usuário ou email',
    'profile.skipPasswordDisabled': 'Agora será necessária senha para entrar',
    'profile.biometricLogin': 'Login Biométrico',
    'profile.biometricLoginDesc': 'Em breve disponível',
    'profile.comingSoon': 'Em Breve',
    'profile.autoLogout': 'Logout Automático',
    'profile.autoLogoutDesc': 'Sair automaticamente após inatividade',
    'profile.autoLogoutNever': 'Nunca',
    'profile.autoLogout5min': '5 minutos',
    'profile.autoLogout15min': '15 minutos',
    'profile.autoLogout30min': '30 minutos',
    'profile.selectCurrency': 'Selecionar Moeda',
    
    // Notifications
    'notifications.expenseAdded': 'Nova despesa adicionada',
    'notifications.expenseAddedDesc': 'Notificar quando uma despesa for adicionada aos seus eventos',
    'notifications.paymentReceived': 'Pagamento recebido',
    'notifications.paymentReceivedDesc': 'Notificar quando você receber um pagamento',
    'notifications.eventUpdated': 'Evento atualizado',
    'notifications.eventUpdatedDesc': 'Notificar quando um evento for atualizado',
    'notifications.weeklyReport': 'Resumo semanal',
    'notifications.weeklyReportDesc': 'Receber um resumo de suas despesas semanalmente',
    
    // Events
    'events.title': 'Meus Eventos',
    'events.create': 'Criar Evento',
    'events.edit': 'Editar Evento',
    'events.delete': 'Excluir Evento',
    'events.deleteConfirm': 'Excluir evento?',
    'events.deleteMessage': 'Isso excluirá o evento e todas as suas despesas',
    'events.name': 'Nome do Evento',
    'events.description': 'Descrição',
    'events.date': 'Data',
    'events.participants': 'Participantes',
    'events.addParticipant': 'Adicionar Participante',
    'events.noEvents': 'Sem eventos',
    'events.noEventsDesc': 'Crie seu primeiro evento para começar',
    'events.active': 'Ativo',
    'events.completed': 'Concluído',
    'events.archived': 'Arquivado',
    'events.finished': 'Finalizado',
    'events.summary': 'Resumo',
    'events.settlements': 'Liquidações',
    'events.payments': 'Pagamentos',
    'events.share': 'Compartilhar',
    'events.options': 'Opções',
    'events.complete': 'Completar',
    'events.archive': 'Arquivar',
    'events.information': 'Informações do Evento',
    'events.reactivate': 'Reativar',
    
    // Expenses
    'expenses.title': 'Despesas',
    'expenses.create': 'Criar Despesa',
    'expenses.edit': 'Editar Despesa',
    'expenses.delete': 'Excluir Despesa',
    'expenses.deleteConfirm': 'Excluir despesa?',
    'expenses.deleteMessage': 'Isso excluirá permanentemente a despesa',
    'expenses.description': 'Descrição da Despesa',
    'expenses.amount': 'Valor',
    'expenses.paidBy': 'Pago por',
    'expenses.splitBetween': 'Dividido entre',
    'expenses.date': 'Data',
    'expenses.category': 'Categoria',
    'expenses.noExpenses': 'Sem despesas',
    'expenses.noExpensesDesc': 'Adicione sua primeira despesa',
    'expenses.total': 'Total',
    'expenses.division': 'Divisão',
    'expenses.selectAll': 'Selecionar Todos',
    'expenses.equally': 'Dividir Igualmente',
    'expenses.custom': 'Divisão Personalizada',
    'expenses.saved': 'Despesa salva',
    'expenses.search': 'Buscar despesas...',
    'expenses.byParticipant': 'Despesas por Participante',
    'expenses.byCategory': 'Despesas por Categoria',
    'expenses.filters': 'Filtros',
    'expenses.filterBy': 'Filtrar por',
    'expenses.sortBy': 'Ordenar por',
    'expenses.category': 'Categoria',
    'expenses.payer': 'Pagador',
    'expenses.amount': 'Valor',
    'expenses.date': 'Data',
    'expenses.description': 'Descrição',
    'expenses.all': 'Todos',
    'expenses.clearFilters': 'Limpar Filtros',
    
    // Participants
    'participants.title': 'Participantes',
    'participants.add': 'Adicionar Participante',
    'participants.select': 'Selecionar Participante',
    'participants.noParticipants': 'Sem participantes',
    'participants.noParticipantsDesc': 'Adicione participantes para começar',
    'participants.name': 'Nome',
    'participants.email': 'Email',
    'participants.phone': 'Telefone',
    'participants.balance': 'Saldo',
    'participants.owes': 'Deve',
    'participants.owed': 'Recebe',
    'participants.search': 'Buscar participantes...',
    
    // Friends
    'friends.title': 'Meus Amigos',
    'friends.add': 'Adicionar Amigo',
    'friends.edit': 'Editar Amigo',
    'friends.delete': 'Excluir Amigo',
    'friends.deleteConfirm': 'Excluir amigo?',
    'friends.deleteMessage': 'Isso removerá o amigo da sua lista',
    'friends.noFriends': 'Sem amigos',
    'friends.noFriendsDesc': 'Adicione amigos para facilitar a criação de eventos',
    'friends.saved': 'Amigo salvo',
    
    // Payments
    'payments.title': 'Pagamentos',
    'payments.record': 'Registrar Pagamento',
    'payments.markAsPaid': 'Marcar como Pago',
    'payments.paid': 'PAGO',
    'payments.pending': 'Pendente',
    'payments.confirmed': 'Confirmado',
    'payments.from': 'De',
    'payments.to': 'Para',
    'payments.amount': 'Valor',
    'payments.date': 'Data',
    'payments.confirmPayment': 'Confirmar Pagamento',
    'payments.confirmMessage': 'Marcar este pagamento como concluído?',
    'payments.recorded': 'Pagamento registrado',
    
    // Summary
    'summary.title': 'Resumo',
    'summary.totalSpent': 'Total Gasto',
    'summary.yourShare': 'Sua Parte',
    'summary.balance': 'Saldo',
    'summary.settlements': 'Liquidações',
    'summary.youOwe': 'Você deve',
    'summary.owesYou': 'Deve a você',
    'summary.settled': 'Liquidado',
    'summary.shareViaWhatsApp': 'Compartilhar via WhatsApp',
    
    // Categories
    'category.food': 'Comida',
    'category.transport': 'Transporte',
    'category.accommodation': 'Acomodação',
    'category.entertainment': 'Entretenimento',
    'category.shopping': 'Compras',
    'category.other': 'Outro',
    
    // Messages
    'message.selectLanguage': 'Selecionar Idioma',
    'message.eventNotEditable': 'Evento Não Editável',
    'message.canOnlyAddExpensesActive': 'Você só pode adicionar despesas em eventos ativos',
    'message.canOnlyEditExpensesActive': 'Você só pode editar despesas em eventos ativos',
    'message.canOnlyDeleteExpensesActive': 'Você só pode excluir despesas em eventos ativos',
    'message.canOnlyEditParticipantsActive': 'Você só pode editar participantes em eventos ativos',
    'message.canOnlyDeleteParticipantsActive': 'Você só pode excluir participantes em eventos ativos',
    'message.nameRequired': 'Nome é obrigatório',
    'message.expenseDeletedSuccess': 'Despesa excluída com sucesso',
    'message.expenseDeletedError': 'Não foi possível excluir a despesa',
    'message.participantUpdatedSuccess': 'Participante atualizado com sucesso',
    'message.participantUpdatedError': 'Não foi possível atualizar o participante',
    'message.participantDeletedSuccess': 'Participante excluído com sucesso',
    'message.participantDeletedError': 'Não foi possível excluir o participante',
    'message.convertedToFriend': 'Convertido em Amigo',
    'message.nowPermanentFriend': 'agora é um amigo permanente e aparecerá em \"Meus Amigos\"',
    'message.updated': 'Atualizado',
    'message.paymentStateError': 'Não foi possível atualizar o status do pagamento',
    'message.receiptAdded': 'Comprovante adicionado',
    'message.receiptRemoved': 'Comprovante removido',
    'message.receiptError': 'Não foi possível atualizar o comprovante',
    'message.eventCompleted': 'Evento Concluído',
    'message.eventCompletedDesc': 'O evento está marcado como concluído. Você pode gerenciar pagamentos.',
    'message.eventCompletedError': 'Não foi possível concluir o evento',
    'message.eventArchived': 'Evento Arquivado',
    'message.eventArchivedDesc': 'O evento foi arquivado com sucesso',
    'message.eventArchivedError': 'Não foi possível arquivar o evento',
    'message.expenseAdded': 'Despesa adicionada',
    'message.expenseAddedDesc': 'A despesa foi adicionada com sucesso',
    'message.participantAdded': 'Participante adicionado',
    'message.participantAddedDesc': 'foi adicionado ao evento',
    'message.participantAddedError': 'Não foi possível adicionar o participante',
    'message.receiptAddedSuccess': 'Comprovante adicionado com sucesso',
    'message.receiptAddedError': 'Não foi possível adicionar o comprovante',
    'message.noSettlements': 'Sem liquidações',
    'message.noSettlementsDesc': 'Não há liquidações pendentes para criar pagamentos',
    'message.whatsappNotAvailable': 'WhatsApp não disponível',
    'message.copiedToClipboard': 'foi copiado para a área de transferência. Você pode colar em qualquer app.',
    'message.whatsappError': 'Erro ao abrir WhatsApp',
    'message.eventStateChangeError': 'Não foi possível alterar o status do evento',
    'message.eventDeletedError': 'Não foi possível excluir o evento',
    'message.markAsComplete': 'Marcar como Concluído',
    'message.markAsCompleteDesc': 'Marcar o evento como concluído bloqueará despesas e participantes, mas você pode gerenciar pagamentos de liquidação.\n\nDeseja continuar?',
    'message.markComplete': 'Marcar Concluído',
    'message.reactivateEvent': 'Reativar Evento',
    'message.reactivateEventDesc': 'Deseja reativar o evento? Você poderá editar despesas e participantes novamente.',
    'message.markAsCompleteShort': 'Deseja marcar o evento como concluído? Despesas e participantes serão bloqueados, mas você pode gerenciar pagamentos.',
    'message.eventReactivated': 'Evento Reativado',
    'message.eventActiveAgain': 'O evento está ativo novamente',
    'message.eventCompletedShort': 'O evento está marcado como concluído. Você pode gerenciar pagamentos.',
    'message.archiveEvent': 'Arquivar Evento',
    'message.archiveEventDesc': 'O evento arquivado só será visível no histórico. Você pode reativá-lo quando quiser.',
    'common.success': 'Sucesso',
    'message.paymentsCreated': 'pagamento criado com sucesso',
    'message.paymentsCreatedPlural': 'pagamentos criados com sucesso',
    'message.eventDeleted': 'Evento excluído com sucesso',
    'message.enterExpenseDescription': 'Digite a descrição da despesa:',
    'message.paymentFromSettlement': 'Pagamento criado do acordo',
    'message.couldNotCreatePayments': 'Não foi possível criar os pagamentos',
    'settlement.addReceipt': 'Adicionar Comprovante',
    'settlement.chooseOption': 'Escolha uma opção',
    'settlement.takePhoto': 'Tirar Foto',
    'settlement.chooseFromGallery': 'Escolher da Galeria',
    'settlement.deleteReceipt': 'Excluir Comprovante',
    'settlement.permissionRequired': 'Permissão necessária',
    'settlement.galleryPermissionDesc': 'Para selecionar uma imagem da galeria, precisamos de permissões de acesso. Por favor, habilite as permissões nas configurações do aplicativo.',
    'settlement.openSettings': 'Abrir Configurações',
    'settlement.galleryError': 'Não foi possível abrir a galeria. Tente novamente.',
    'settlement.permissionDenied': 'Permissão negada',
    'settlement.cameraPermissionDesc': 'Precisamos de acesso à câmera',
    'participant.info': 'Informações do Participante',
    'expenses.title': 'Despesas',
    'expenses.paidBy': 'Pago por',
    'expenses.division': 'Divisão',
    'expenses.excluded': 'Excluídos',
    'expenses.edit': 'Editar',
    'expenses.delete': 'Excluir',
    'expenses.noExpenses': 'Nenhuma despesa registrada',
    'expenses.noExpensesDesc': 'Toque "Adicionar" para criar a primeira despesa',
    'expenses.noResults': 'Nenhuma despesa encontrada',
    'expenses.noResultsDesc': 'Tente com outros filtros ou busca',
    'receipt.label': 'Comprovante',
    'message.chooseLanguage': 'Escolha seu idioma preferido',
    'message.noParticipantsSelected': 'Selecione pelo menos um participante',
    'message.fillAllFields': 'Preencha todos os campos obrigatórios',
    'message.invalidAmount': 'Digite um valor válido',
    'message.eventCreated': 'Evento criado com sucesso',
    'message.eventUpdated': 'Evento atualizado',
    'message.expenseCreated': 'Despesa criada com sucesso',
    'message.expenseUpdated': 'Despesa atualizada',
    'message.confirmDelete': 'Confirmar exclusão',
    
    // Additional translations for Portuguese
    'common.add': 'Adicionar',
    'common.success': 'Sucesso',
    'common.error': 'Erro',
    'common.cancel': 'Cancelar',
    'participants.title': 'Participantes',
    'participants.search': 'Buscar participantes...',
    'participants.noParticipants': 'Não há participantes',
    'participants.noParticipantsDesc': 'Adicione participantes para dividir despesas',
    'participants.balance': 'Saldo',
    'participants.owes': 'Deve receber',
    'participants.shouldPay': 'Deve pagar',
    'participants.balanced': 'Equilibrado',
    'participants.contactInfo': 'Informações de Contato',
    'participants.additionalInfo': 'Informações Adicionais',
    'participants.addedToEvent': 'Adicionado ao evento',
    'participants.noContactInfo': 'Nenhuma informação de contato disponível',
    'participants.friendPermanent': 'Amigo Permanente',
    'participants.temporaryParticipant': 'Participante Temporário',
    'participant.info': 'Informações do Participante',
    'expenses.detailTitle': 'Detalhes da Despesa',
    'expenses.generalInfo': 'Informações Gerais',
    'expenses.excludedParticipants': 'Participantes Excluídos',
    'expenses.expenseDivision': 'Divisão da Despesa',
    'expenses.receipt': 'Comprovante',
    'expenses.description': 'Descrição',
    'expenses.amount': 'Valor',
    'expenses.date': 'Data',
    'expenses.category': 'Categoria',
    'expenses.noCategory': 'Sem categoria',
    'expenses.paidBy': 'Pago por',
    'expenses.participants': 'participantes',
    'summary.title': 'Resumo',
    // AddParticipantModal
    'addParticipant.title': 'Adicionar Participantes',
    'addParticipant.tabFriends': 'Meus Amigos',
    'addParticipant.tabNew': 'Novo',
    'addParticipant.tabBulk': 'Em Massa',
    'addParticipant.searchPlaceholder': 'Buscar amigos...',
    'addParticipant.selectAll': 'Selecionar todos',
    'addParticipant.deselectAll': 'Desselecionar todos',
    'addParticipant.selectionCounter': '{selected} de {total}',
    'addParticipant.noFriends': 'Não há amigos disponíveis',
    'addParticipant.noFriendsDesc': 'Adicione amigos na seção "Meus Amigos" para selecioná-los rapidamente',
    'addParticipant.createNewParticipant': 'Criar Novo Participante',
    'addParticipant.selectHint': 'Toque para selecionar amigos. Você pode escolher vários de uma vez.',
    'addParticipant.noSearchResults': 'Nenhum amigo encontrado',
    'addParticipant.noSearchResultsDesc': 'Tente outro termo de busca',
    'addParticipant.selectedCount': '{count} amigo{plural} selecionado{pluralSelected}',
    'addParticipant.clear': 'Limpar',
    'addParticipant.addFriend': 'Adicionar Amigo',
    'addParticipant.addFriends': 'Adicionar {count} Amigos',
    'addParticipant.bulkTitle': 'Adicionar Participantes em Massa',
    'addParticipant.bulkSubtitle': 'Cria múltiplos participantes temporários de uma vez',
    'addParticipant.bulkRestricted': 'Carga em Massa Restrita',
    'addParticipant.bulkRestrictedMessage': 'A carga em massa de participantes só pode ser feita quando o evento não possui despesas registradas.',
    'addParticipant.bulkRestrictedSuggestion': 'Você pode adicionar participantes individualmente usando as abas "Meus Amigos" ou "Novo".',
    'addParticipant.customNames': 'Nomes Próprios',
    'addParticipant.generic': 'Genéricos',
    'addParticipant.namesLabel': 'Nomes dos Participantes',
    'addParticipant.namesPlaceholder': 'Digite um nome por linha:\n\nJoão Silva\nMaria Santos\nCarlos Lima\n...',
    'addParticipant.namesHint': '💡 Escreva um nome por linha. Sem limite de participantes.',
    'addParticipant.quantityLabel': 'Quantidade de Participantes',
    'addParticipant.genericPreview': 'Serão criados: Participante 1, Participante 2, ... Participante {count}',
    'addParticipant.genericHint': '💡 Faixa: 1 a 50 participantes genéricos',
    'addParticipant.createParticipants': 'Criar Participantes',
    'addParticipant.createGeneric': 'Criar {count} Participantes',
    'addParticipant.newTitle': 'Criar Novo Participante',
    'addParticipant.fullNameLabel': 'Nome Completo *',
    'addParticipant.fullNamePlaceholder': 'Nome do participante',
    'addParticipant.cbuLabel': 'PIX/Conta (Opcional)',
    'addParticipant.cbuPlaceholder': 'PIX ou conta para pagamentos',
    'addParticipant.phoneLabel': 'Telefone (Opcional)',
    'addParticipant.phonePlaceholder': '+55 11 9876-5432',
    'addParticipant.emailLabel': 'Email (Opcional)',
    'addParticipant.emailPlaceholder': 'email@exemplo.com',
    'addParticipant.saveAsFriend': 'Salvar como amigo permanente',
    'addParticipant.saveAsFriendDesc': 'Você poderá reutilizar este contato em eventos futuros',
    'addParticipant.saveAndAdd': 'Salvar Amigo e Adicionar',
    'addParticipant.createAndAdd': 'Criar e Adicionar',
    // AddParticipant Alerts
    'addParticipant.error.selectFriends': 'Selecione pelo menos um amigo para adicionar',
    'addParticipant.error.nameRequired': 'O nome é obrigatório',
    'addParticipant.error.createParticipant': 'Não foi possível criar o participante',
    'addParticipant.error.createBulk': 'Não foi possível criar os participantes',
    'addParticipant.error.atLeastOneName': 'Digite pelo menos um nome',
    'addParticipant.error.numberRange': 'O número deve estar entre 1 e 50',
    'addParticipant.alert.bulkRestricted': '🚫 Carga em Massa Restrita',
    'addParticipant.alert.bulkRestrictedMessage': 'A carga em massa de participantes não pode ser usada quando o evento já possui despesas registradas.\n\nVocê pode adicionar participantes individualmente usando "Meus Amigos" ou "Novo".',
    'addParticipant.alert.understood': 'Entendido',
    'addParticipant.alert.participantsAdded': '✅ Participantes Adicionados',
    'addParticipant.alert.participantsAddedMessage': '{count} participante{plural} adicionado{pluralSelected} com sucesso',
  // ProfileScreen Privacy Section
  'profile.privacy': 'Privacidade',
  'profile.shareEmail': 'Compartilhar email',
  'profile.shareEmailDesc': 'Permitir que outros usuários vejam seu email',
  'profile.sharePhone': 'Compartilhar telefone',
  'profile.sharePhoneDesc': 'Permitir que outros usuários vejam seu telefone',
  'profile.allowInvitations': 'Permitir convites',
  'profile.allowInvitationsDesc': 'Receber convites para eventos de outros usuários',
  // ProfileScreen Data Section
  'profile.dataBackup': 'Dados e Backup',
  'profile.exportData': 'Exportar dados',
  'profile.exportDataDesc': 'Baixar uma cópia dos seus dados',
  'profile.deleteAllData': 'Excluir todos os dados',
  'profile.deleteAllDataDesc': 'Apagar permanentemente todas as informações',
  // ProfileScreen Information Section
  'profile.information': 'Informações',
  'profile.appVersion': 'Versão do app',
  'profile.termsOfService': 'Termos de serviço',
  'profile.privacyPolicy': 'Política de privacidade',
  'profile.contactSupport': 'Contatar suporte',
  // ProfileScreen Messages
  'profile.message.selectLanguage': 'Selecionar idioma',
  'profile.message.pickImageError': 'Não foi possível selecionar a imagem',
  'profile.message.takePhotoError': 'Não foi possível tirar a foto',
  'profile.message.updateAvatarSuccess': 'Foto de perfil atualizada',
  'profile.message.updateAvatarError': 'Não foi possível atualizar a foto de perfil',
  'profile.message.exportDataTitle': 'Exportar Dados',
  'profile.message.exportDataMessage': 'Que dados você deseja exportar?',
  'profile.message.allData': 'Todos os dados',
  'profile.message.exportSuccess': 'Dados exportados com sucesso',
  'profile.message.exportError': 'Não foi possível exportar os dados',
  'profile.message.deleteAllDataTitle': '⚠️ Excluir Todos os Dados',
  'profile.message.deleteAllDataMessage': 'Esta ação excluirá permanentemente todos os seus eventos, despesas e participantes. Tem certeza?',
  'profile.message.deleteAll': 'Excluir Tudo',
  'profile.message.deleteCompleted': 'Todos os dados foram excluídos',
  'profile.message.deleteError': 'Não foi possível excluir os dados',
  'profile.message.logoutTitle': 'Encerrar Sessão',
  'profile.message.logoutMessage': 'Tem certeza de que deseja encerrar a sessão?',
  'profile.message.changeAvatarTitle': 'Alterar foto de perfil',
  'profile.message.chooseOption': 'Escolha uma opção',
  'profile.message.takePhoto': 'Tirar Foto',
  'profile.message.chooseFromGallery': 'Escolher da Galeria',
  'profile.message.removePhoto': 'Remover Foto',
  'profile.message.permissionRequired': 'Permissão necessária',
  'profile.message.galleryPermission': 'Precisamos de permissão para acessar suas fotos',
  'profile.message.cameraPermission': 'Precisamos de permissão para acessar sua câmera',
  'profile.message.comingSoon': 'Em breve',
  'profile.message.userNotFound': 'Não foi possível identificar o usuário',
  'profile.message.profileSaved': 'Perfil atualizado corretamente',
  'profile.message.profileSaveError': 'Não foi possível salvar o perfil',
  'profile.message.passwordTooShort': 'A senha deve ter pelo menos 6 caracteres',
  'profile.message.passwordChangeError': 'Não foi possível alterar a senha',
  'profile.message.settingUpdateError': 'Não foi possível atualizar a configuração',
  'profile.message.currencySelector': 'Seletor de moeda em breve',
  'profile.message.termsComingSoon': 'Termos de serviço em breve',
  'profile.message.privacyComingSoon': 'Política de privacidade em breve',
  'profile.message.supportComingSoon': 'Suporte em breve',
  // Novos campos ProfileScreen
  'profile.username': 'Usuário',
  'profile.shareEvent': 'Compartilhar Evento',
  'profile.shareEventDesc': 'Permitir que outros usuários participem do carregamento de eventos',
  'profile.importData': 'Importar dados',
  'profile.importDataDesc': 'Carregar dados de um arquivo de backup',
  'profile.aboutApp': 'Sobre...',
  'profile.previousVersions': 'Versões Anteriores',
  'profile.version': 'Versão',
  'profile.releaseNotes': 'Notas da versão',
  'profile.bugs': 'Erros corrigidos',
  'profile.improvements': 'Melhorias',
  'profile.newFeatures': 'Novas funcionalidades',
  // Mensagens de importação
  'profile.message.importDataTitle': 'Importar Dados',
  'profile.message.importDataMessage': 'Os dados atuais serão substituídos',
  'profile.message.selectFile': 'Selecionar Arquivo',
  'profile.message.currentData': 'Dados atuais',
  'profile.message.newData': 'Dados a importar',
  'profile.message.importSuccess': 'Dados importados com sucesso',
  'profile.message.importError': 'Erro ao importar dados',
  'profile.message.aboutComingSoon': 'Informações em breve'
  }
};

const LanguageContext = createContext<LanguageContextValue>({
  language: 'es',
  setLanguage: () => {},
  t: (key: string, params?: Record<string, string | number>) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = key;

    // Usar siempre las traducciones embebidas como fuente principal
    translation = translations[language][key as keyof typeof translations['es']] || 
                 additionalEsTranslations[key as keyof typeof additionalEsTranslations] || 
                 key;
    
    // Interpolación de variables: reemplaza {variable} con el valor
    if (params) {
      Object.keys(params).forEach(param => {
        const regex = new RegExp(`{${param}}`, 'g');
        translation = translation.replace(regex, String(params[param]));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);