import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'pt';

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string; // función de traducción simple
}

// Traducciones completas embebidas (offline-first)
const translations = {
  es: {
    // General
    'app.name': 'SplitSmart',
    'welcome': 'Bienvenido',
    'login': 'Iniciar Sesión',
    'logout': 'Cerrar Sesión',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'edit': 'Editar',
    'delete': 'Eliminar',
    'confirm': 'Confirmar',
    'close': 'Cerrar',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'all': 'Todos',
    'yes': 'Sí',
    'no': 'No',
    'ok': 'OK',
    'error': 'Error',
    'success': 'Éxito',
    'loading': 'Cargando...',
    'noData': 'Sin datos',
    'optional': 'Opcional',
    
    // Navigation
    'home': 'Inicio',
    'events': 'Eventos',
    'expenses': 'Gastos',
    'participants': 'Participantes',
    'profile': 'Perfil',
    'settings': 'Configuración',
    'friends': 'Amigos',
    
    // Profile
    'profile.title': 'Mi Perfil',
    'profile.edit': 'Editar Perfil',
    'profile.stats': 'Estadísticas',
    'profile.activeEvents': 'Eventos Activos',
    'profile.totalExpenses': 'Gastos Total',
    'profile.totalSpent': 'Gastado Total',
    'profile.friendsCount': 'Amigos',
    'profile.personalInfo': 'Información Personal',
    'profile.name': 'Nombre Completo',
    'profile.email': 'Email',
    'profile.phone': 'Teléfono',
    'profile.cbu': 'CBU/Alias',
    'profile.preferences': 'Preferencias',
    'profile.theme': 'Tema',
    'profile.themeDark': 'Oscuro',
    'profile.themeLight': 'Claro',
    'profile.currency': 'Moneda Preferida',
    'profile.language': 'Idioma',
    'profile.notifications': 'Notificaciones',
    'profile.security': 'Seguridad',
    'profile.changePassword': 'Cambiar Contraseña',
    'profile.skipPassword': 'Ingreso sin contraseña',
    'profile.skipPasswordOn': 'No se solicitará contraseña al iniciar sesión',
    'profile.skipPasswordOff': 'Se solicitará contraseña al iniciar sesión',
    'profile.saveChanges': 'Guardar Cambios',
    'profile.newPassword': 'Nueva Contraseña',
    'profile.updatePassword': 'Actualizar Contraseña',
    'profile.passwordUpdated': '¡Contraseña actualizada!',
    'profile.passwordUpdateSuccess': 'Tu contraseña ha sido cambiada exitosamente',
    'profile.skipPasswordUpdated': '¡Actualizado!',
    'profile.skipPasswordEnabled': 'Ahora puedes ingresar solo con tu usuario o email',
    'profile.skipPasswordDisabled': 'Ahora se requerirá contraseña para ingresar',
    
    // Notifications
    'notifications.expenseAdded': 'Nuevo gasto agregado',
    'notifications.expenseAddedDesc': 'Notificar cuando se agregue un gasto a tus eventos',
    'notifications.paymentReceived': 'Pago recibido',
    'notifications.paymentReceivedDesc': 'Notificar cuando recibas un pago',
    'notifications.eventUpdated': 'Evento actualizado',
    'notifications.eventUpdatedDesc': 'Notificar cuando se actualice un evento',
    'notifications.weeklyReport': 'Resumen semanal',
    'notifications.weeklyReportDesc': 'Recibir un resumen de tus gastos semanalmente',
    
    // Events
    'events.title': 'Mis Eventos',
    'events.create': 'Crear Evento',
    'events.edit': 'Editar Evento',
    'events.delete': 'Eliminar Evento',
    'events.deleteConfirm': '¿Eliminar evento?',
    'events.deleteMessage': 'Se eliminará el evento y todos sus gastos',
    'events.name': 'Nombre del Evento',
    'events.description': 'Descripción',
    'events.date': 'Fecha',
    'events.participants': 'Participantes',
    'events.addParticipant': 'Agregar Participante',
    'events.noEvents': 'No hay eventos',
    'events.noEventsDesc': 'Crea tu primer evento para comenzar',
    'events.active': 'Activo',
    'events.finished': 'Finalizado',
    'events.summary': 'Resumen',
    'events.settlements': 'Liquidaciones',
    'events.payments': 'Pagos',
    'events.share': 'Compartir',
    'events.options': 'Opciones',
    
    // Expenses
    'expenses.title': 'Gastos',
    'expenses.create': 'Crear Gasto',
    'expenses.edit': 'Editar Gasto',
    'expenses.delete': 'Eliminar Gasto',
    'expenses.deleteConfirm': '¿Eliminar gasto?',
    'expenses.deleteMessage': 'Se eliminará el gasto permanentemente',
    'expenses.description': 'Descripción del Gasto',
    'expenses.amount': 'Monto',
    'expenses.paidBy': 'Pagado por',
    'expenses.splitBetween': 'Dividido entre',
    'expenses.date': 'Fecha',
    'expenses.category': 'Categoría',
    'expenses.noExpenses': 'No hay gastos',
    'expenses.noExpensesDesc': 'Agrega tu primer gasto',
    'expenses.total': 'Total',
    'expenses.division': 'División',
    'expenses.selectAll': 'Seleccionar Todos',
    'expenses.equally': 'Dividir Equitativamente',
    'expenses.custom': 'División Personalizada',
    'expenses.saved': 'Gasto guardado',
    
    // Participants
    'participants.title': 'Participantes',
    'participants.add': 'Agregar Participante',
    'participants.select': 'Seleccionar Participante',
    'participants.noParticipants': 'No hay participantes',
    'participants.noParticipantsDesc': 'Agrega participantes para comenzar',
    'participants.name': 'Nombre',
    'participants.email': 'Email',
    'participants.phone': 'Teléfono',
    'participants.balance': 'Balance',
    'participants.owes': 'Debe',
    'participants.owed': 'Le deben',
    
    // Friends
    'friends.title': 'Mis Amigos',
    'friends.add': 'Agregar Amigo',
    'friends.edit': 'Editar Amigo',
    'friends.delete': 'Eliminar Amigo',
    'friends.deleteConfirm': '¿Eliminar amigo?',
    'friends.deleteMessage': 'Se eliminará el amigo de tu lista',
    'friends.noFriends': 'No hay amigos',
    'friends.noFriendsDesc': 'Agrega amigos para facilitar la creación de eventos',
    'friends.saved': 'Amigo guardado',
    
    // Payments
    'payments.title': 'Pagos',
    'payments.record': 'Registrar Pago',
    'payments.markAsPaid': 'Marcar como Pagado',
    'payments.paid': 'PAGADO',
    'payments.pending': 'Pendiente',
    'payments.confirmed': 'Confirmado',
    'payments.from': 'De',
    'payments.to': 'Para',
    'payments.amount': 'Monto',
    'payments.date': 'Fecha',
    'payments.confirmPayment': 'Confirmar Pago',
    'payments.confirmMessage': '¿Marcar este pago como realizado?',
    'payments.recorded': 'Pago registrado',
    
    // Summary
    'summary.title': 'Resumen',
    'summary.totalSpent': 'Total Gastado',
    'summary.yourShare': 'Tu Parte',
    'summary.balance': 'Balance',
    'summary.settlements': 'Liquidaciones',
    'summary.youOwe': 'Debes',
    'summary.owesYou': 'Te debe',
    'summary.settled': 'Liquidado',
    'summary.shareViaWhatsApp': 'Compartir por WhatsApp',
    
    // Categories
    'category.food': 'Comida',
    'category.transport': 'Transporte',
    'category.accommodation': 'Alojamiento',
    'category.entertainment': 'Entretenimiento',
    'category.shopping': 'Compras',
    'category.other': 'Otro',
    
    // Messages
    'message.selectLanguage': 'Seleccionar Idioma',
    'message.chooseLanguage': 'Elige tu idioma preferido',
    'message.noParticipantsSelected': 'Selecciona al menos un participante',
    'message.fillAllFields': 'Completa todos los campos requeridos',
    'message.invalidAmount': 'Ingresa un monto válido',
    'message.eventCreated': 'Evento creado exitosamente',
    'message.eventUpdated': 'Evento actualizado',
    'message.expenseCreated': 'Gasto creado exitosamente',
    'message.expenseUpdated': 'Gasto actualizado',
    'message.confirmDelete': 'Confirmar eliminación',
  },
  en: {
    // General
    'app.name': 'SplitSmart',
    'welcome': 'Welcome',
    'login': 'Sign In',
    'logout': 'Sign Out',
    'cancel': 'Cancel',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'close': 'Close',
    'search': 'Search',
    'filter': 'Filter',
    'all': 'All',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'error': 'Error',
    'success': 'Success',
    'loading': 'Loading...',
    'noData': 'No data',
    'optional': 'Optional',
    
    // Navigation
    'home': 'Home',
    'events': 'Events',
    'expenses': 'Expenses',
    'participants': 'Participants',
    'profile': 'Profile',
    'settings': 'Settings',
    'friends': 'Friends',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.edit': 'Edit Profile',
    'profile.stats': 'Statistics',
    'profile.activeEvents': 'Active Events',
    'profile.totalExpenses': 'Total Expenses',
    'profile.totalSpent': 'Total Spent',
    'profile.friendsCount': 'Friends',
    'profile.personalInfo': 'Personal Information',
    'profile.name': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.cbu': 'Bank Account',
    'profile.preferences': 'Preferences',
    'profile.theme': 'Theme',
    'profile.themeDark': 'Dark',
    'profile.themeLight': 'Light',
    'profile.currency': 'Preferred Currency',
    'profile.language': 'Language',
    'profile.notifications': 'Notifications',
    'profile.security': 'Security',
    'profile.changePassword': 'Change Password',
    'profile.skipPassword': 'Login without password',
    'profile.skipPasswordOn': 'Password will not be required at login',
    'profile.skipPasswordOff': 'Password will be required at login',
    'profile.saveChanges': 'Save Changes',
    'profile.newPassword': 'New Password',
    'profile.updatePassword': 'Update Password',
    'profile.passwordUpdated': 'Password updated!',
    'profile.passwordUpdateSuccess': 'Your password has been changed successfully',
    'profile.skipPasswordUpdated': 'Updated!',
    'profile.skipPasswordEnabled': 'You can now login with just your username or email',
    'profile.skipPasswordDisabled': 'Password will now be required to login',
    
    // Notifications
    'notifications.expenseAdded': 'New expense added',
    'notifications.expenseAddedDesc': 'Notify when an expense is added to your events',
    'notifications.paymentReceived': 'Payment received',
    'notifications.paymentReceivedDesc': 'Notify when you receive a payment',
    'notifications.eventUpdated': 'Event updated',
    'notifications.eventUpdatedDesc': 'Notify when an event is updated',
    'notifications.weeklyReport': 'Weekly summary',
    'notifications.weeklyReportDesc': 'Receive a summary of your expenses weekly',
    
    // Events
    'events.title': 'My Events',
    'events.create': 'Create Event',
    'events.edit': 'Edit Event',
    'events.delete': 'Delete Event',
    'events.deleteConfirm': 'Delete event?',
    'events.deleteMessage': 'This will delete the event and all its expenses',
    'events.name': 'Event Name',
    'events.description': 'Description',
    'events.date': 'Date',
    'events.participants': 'Participants',
    'events.addParticipant': 'Add Participant',
    'events.noEvents': 'No events',
    'events.noEventsDesc': 'Create your first event to get started',
    'events.active': 'Active',
    'events.finished': 'Finished',
    'events.summary': 'Summary',
    'events.settlements': 'Settlements',
    'events.payments': 'Payments',
    'events.share': 'Share',
    'events.options': 'Options',
    
    // Expenses
    'expenses.title': 'Expenses',
    'expenses.create': 'Create Expense',
    'expenses.edit': 'Edit Expense',
    'expenses.delete': 'Delete Expense',
    'expenses.deleteConfirm': 'Delete expense?',
    'expenses.deleteMessage': 'This will permanently delete the expense',
    'expenses.description': 'Expense Description',
    'expenses.amount': 'Amount',
    'expenses.paidBy': 'Paid by',
    'expenses.splitBetween': 'Split between',
    'expenses.date': 'Date',
    'expenses.category': 'Category',
    'expenses.noExpenses': 'No expenses',
    'expenses.noExpensesDesc': 'Add your first expense',
    'expenses.total': 'Total',
    'expenses.division': 'Division',
    'expenses.selectAll': 'Select All',
    'expenses.equally': 'Split Equally',
    'expenses.custom': 'Custom Split',
    'expenses.saved': 'Expense saved',
    
    // Participants
    'participants.title': 'Participants',
    'participants.add': 'Add Participant',
    'participants.select': 'Select Participant',
    'participants.noParticipants': 'No participants',
    'participants.noParticipantsDesc': 'Add participants to get started',
    'participants.name': 'Name',
    'participants.email': 'Email',
    'participants.phone': 'Phone',
    'participants.balance': 'Balance',
    'participants.owes': 'Owes',
    'participants.owed': 'Is owed',
    
    // Friends
    'friends.title': 'My Friends',
    'friends.add': 'Add Friend',
    'friends.edit': 'Edit Friend',
    'friends.delete': 'Delete Friend',
    'friends.deleteConfirm': 'Delete friend?',
    'friends.deleteMessage': 'This will remove the friend from your list',
    'friends.noFriends': 'No friends',
    'friends.noFriendsDesc': 'Add friends to make event creation easier',
    'friends.saved': 'Friend saved',
    
    // Payments
    'payments.title': 'Payments',
    'payments.record': 'Record Payment',
    'payments.markAsPaid': 'Mark as Paid',
    'payments.paid': 'PAID',
    'payments.pending': 'Pending',
    'payments.confirmed': 'Confirmed',
    'payments.from': 'From',
    'payments.to': 'To',
    'payments.amount': 'Amount',
    'payments.date': 'Date',
    'payments.confirmPayment': 'Confirm Payment',
    'payments.confirmMessage': 'Mark this payment as completed?',
    'payments.recorded': 'Payment recorded',
    
    // Summary
    'summary.title': 'Summary',
    'summary.totalSpent': 'Total Spent',
    'summary.yourShare': 'Your Share',
    'summary.balance': 'Balance',
    'summary.settlements': 'Settlements',
    'summary.youOwe': 'You owe',
    'summary.owesYou': 'Owes you',
    'summary.settled': 'Settled',
    'summary.shareViaWhatsApp': 'Share via WhatsApp',
    
    // Categories
    'category.food': 'Food',
    'category.transport': 'Transport',
    'category.accommodation': 'Accommodation',
    'category.entertainment': 'Entertainment',
    'category.shopping': 'Shopping',
    'category.other': 'Other',
    
    // Messages
    'message.selectLanguage': 'Select Language',
    'message.chooseLanguage': 'Choose your preferred language',
    'message.noParticipantsSelected': 'Select at least one participant',
    'message.fillAllFields': 'Fill in all required fields',
    'message.invalidAmount': 'Enter a valid amount',
    'message.eventCreated': 'Event created successfully',
    'message.eventUpdated': 'Event updated',
    'message.expenseCreated': 'Expense created successfully',
    'message.expenseUpdated': 'Expense updated',
    'message.confirmDelete': 'Confirm deletion',
  },
  pt: {
    // General
    'app.name': 'SplitSmart',
    'welcome': 'Bem-vindo',
    'login': 'Entrar',
    'logout': 'Sair',
    'cancel': 'Cancelar',
    'save': 'Salvar',
    'edit': 'Editar',
    'delete': 'Excluir',
    'confirm': 'Confirmar',
    'close': 'Fechar',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'all': 'Todos',
    'yes': 'Sim',
    'no': 'Não',
    'ok': 'OK',
    'error': 'Erro',
    'success': 'Sucesso',
    'loading': 'Carregando...',
    'noData': 'Sem dados',
    'optional': 'Opcional',
    
    // Navigation
    'home': 'Início',
    'events': 'Eventos',
    'expenses': 'Despesas',
    'participants': 'Participantes',
    'profile': 'Perfil',
    'settings': 'Configurações',
    'friends': 'Amigos',
    
    // Profile
    'profile.title': 'Meu Perfil',
    'profile.edit': 'Editar Perfil',
    'profile.stats': 'Estatísticas',
    'profile.activeEvents': 'Eventos Ativos',
    'profile.totalExpenses': 'Despesas Totais',
    'profile.totalSpent': 'Total Gasto',
    'profile.friendsCount': 'Amigos',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.name': 'Nome Completo',
    'profile.email': 'Email',
    'profile.phone': 'Telefone',
    'profile.cbu': 'Conta Bancária',
    'profile.preferences': 'Preferências',
    'profile.theme': 'Tema',
    'profile.themeDark': 'Escuro',
    'profile.themeLight': 'Claro',
    'profile.currency': 'Moeda Preferida',
    'profile.language': 'Idioma',
    'profile.notifications': 'Notificações',
    'profile.security': 'Segurança',
    'profile.changePassword': 'Alterar Senha',
    'profile.skipPassword': 'Login sem senha',
    'profile.skipPasswordOn': 'Senha não será solicitada no login',
    'profile.skipPasswordOff': 'Senha será solicitada no login',
    'profile.saveChanges': 'Salvar Alterações',
    'profile.newPassword': 'Nova Senha',
    'profile.updatePassword': 'Atualizar Senha',
    'profile.passwordUpdated': 'Senha atualizada!',
    'profile.passwordUpdateSuccess': 'Sua senha foi alterada com sucesso',
    'profile.skipPasswordUpdated': 'Atualizado!',
    'profile.skipPasswordEnabled': 'Agora você pode entrar apenas com seu usuário ou email',
    'profile.skipPasswordDisabled': 'Agora será necessária senha para entrar',
    
    // Notifications
    'notifications.expenseAdded': 'Nova despesa adicionada',
    'notifications.expenseAddedDesc': 'Notificar quando uma despesa for adicionada aos seus eventos',
    'notifications.paymentReceived': 'Pagamento recebido',
    'notifications.paymentReceivedDesc': 'Notificar quando você receber um pagamento',
    'notifications.eventUpdated': 'Evento atualizado',
    'notifications.eventUpdatedDesc': 'Notificar quando um evento for atualizado',
    'notifications.weeklyReport': 'Resumo semanal',
    'notifications.weeklyReportDesc': 'Receber um resumo de suas despesas semanalmente',
    
    // Events
    'events.title': 'Meus Eventos',
    'events.create': 'Criar Evento',
    'events.edit': 'Editar Evento',
    'events.delete': 'Excluir Evento',
    'events.deleteConfirm': 'Excluir evento?',
    'events.deleteMessage': 'Isso excluirá o evento e todas as suas despesas',
    'events.name': 'Nome do Evento',
    'events.description': 'Descrição',
    'events.date': 'Data',
    'events.participants': 'Participantes',
    'events.addParticipant': 'Adicionar Participante',
    'events.noEvents': 'Sem eventos',
    'events.noEventsDesc': 'Crie seu primeiro evento para começar',
    'events.active': 'Ativo',
    'events.finished': 'Finalizado',
    'events.summary': 'Resumo',
    'events.settlements': 'Liquidações',
    'events.payments': 'Pagamentos',
    'events.share': 'Compartilhar',
    'events.options': 'Opções',
    
    // Expenses
    'expenses.title': 'Despesas',
    'expenses.create': 'Criar Despesa',
    'expenses.edit': 'Editar Despesa',
    'expenses.delete': 'Excluir Despesa',
    'expenses.deleteConfirm': 'Excluir despesa?',
    'expenses.deleteMessage': 'Isso excluirá permanentemente a despesa',
    'expenses.description': 'Descrição da Despesa',
    'expenses.amount': 'Valor',
    'expenses.paidBy': 'Pago por',
    'expenses.splitBetween': 'Dividido entre',
    'expenses.date': 'Data',
    'expenses.category': 'Categoria',
    'expenses.noExpenses': 'Sem despesas',
    'expenses.noExpensesDesc': 'Adicione sua primeira despesa',
    'expenses.total': 'Total',
    'expenses.division': 'Divisão',
    'expenses.selectAll': 'Selecionar Todos',
    'expenses.equally': 'Dividir Igualmente',
    'expenses.custom': 'Divisão Personalizada',
    'expenses.saved': 'Despesa salva',
    
    // Participants
    'participants.title': 'Participantes',
    'participants.add': 'Adicionar Participante',
    'participants.select': 'Selecionar Participante',
    'participants.noParticipants': 'Sem participantes',
    'participants.noParticipantsDesc': 'Adicione participantes para começar',
    'participants.name': 'Nome',
    'participants.email': 'Email',
    'participants.phone': 'Telefone',
    'participants.balance': 'Saldo',
    'participants.owes': 'Deve',
    'participants.owed': 'Recebe',
    
    // Friends
    'friends.title': 'Meus Amigos',
    'friends.add': 'Adicionar Amigo',
    'friends.edit': 'Editar Amigo',
    'friends.delete': 'Excluir Amigo',
    'friends.deleteConfirm': 'Excluir amigo?',
    'friends.deleteMessage': 'Isso removerá o amigo da sua lista',
    'friends.noFriends': 'Sem amigos',
    'friends.noFriendsDesc': 'Adicione amigos para facilitar a criação de eventos',
    'friends.saved': 'Amigo salvo',
    
    // Payments
    'payments.title': 'Pagamentos',
    'payments.record': 'Registrar Pagamento',
    'payments.markAsPaid': 'Marcar como Pago',
    'payments.paid': 'PAGO',
    'payments.pending': 'Pendente',
    'payments.confirmed': 'Confirmado',
    'payments.from': 'De',
    'payments.to': 'Para',
    'payments.amount': 'Valor',
    'payments.date': 'Data',
    'payments.confirmPayment': 'Confirmar Pagamento',
    'payments.confirmMessage': 'Marcar este pagamento como concluído?',
    'payments.recorded': 'Pagamento registrado',
    
    // Summary
    'summary.title': 'Resumo',
    'summary.totalSpent': 'Total Gasto',
    'summary.yourShare': 'Sua Parte',
    'summary.balance': 'Saldo',
    'summary.settlements': 'Liquidações',
    'summary.youOwe': 'Você deve',
    'summary.owesYou': 'Deve a você',
    'summary.settled': 'Liquidado',
    'summary.shareViaWhatsApp': 'Compartilhar via WhatsApp',
    
    // Categories
    'category.food': 'Comida',
    'category.transport': 'Transporte',
    'category.accommodation': 'Acomodação',
    'category.entertainment': 'Entretenimento',
    'category.shopping': 'Compras',
    'category.other': 'Outro',
    
    // Messages
    'message.selectLanguage': 'Selecionar Idioma',
    'message.chooseLanguage': 'Escolha seu idioma preferido',
    'message.noParticipantsSelected': 'Selecione pelo menos um participante',
    'message.fillAllFields': 'Preencha todos os campos obrigatórios',
    'message.invalidAmount': 'Digite um valor válido',
    'message.eventCreated': 'Evento criado com sucesso',
    'message.eventUpdated': 'Evento atualizado',
    'message.expenseCreated': 'Despesa criada com sucesso',
    'message.expenseUpdated': 'Despesa atualizada',
    'message.confirmDelete': 'Confirmar exclusão',
  }
};

const LanguageContext = createContext<LanguageContextValue>({
  language: 'es',
  setLanguage: () => {},
  t: (key: string) => key
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);